#!/bin/bash
# (needs Linux, java, gcc, python3) tests/bits_rot_test.caspien under everything on, shipped and everything off: output equals tests/bits_rot_test.py;
# with everything on the generated code contains rol and ror instructions (the source is generated by bits_rot_gen.py).
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
W=$(mktemp -d); trap 'rm -rf "$W"' EXIT
export JAVA_TOOL_OPTIONS=
tar -C "$ROOT" --exclude=.git --exclude=.cache -cf - . | tar -C "$W" -xf -
cd "$W" || exit 1
sed -i 's/^target .*/target linux/; s/^\( *\)default: win64/\1default: sysv_x64/' toolchain.config
cp toolchain.config toolchain.config.shipped
python3 tests/bits_rot_test.py > exp.txt
for cfg in SHIPPED FULL OFF; do
  cp toolchain.config.shipped toolchain.config
  python3 - $cfg <<'PY'
import sys
sys.path.insert(0, "benchmarks/nbody")
import bench as B
if sys.argv[1] != "SHIPPED":
    B.patch_config("toolchain.config", getattr(B, sys.argv[1]))
PY
  java Compiler -i tests/bits_rot_test.caspien prog_$cfg --no-cache >compile_$cfg.log 2>&1 || { echo "FAIL: compile ($cfg)"; tail -5 compile_$cfg.log; exit 1; }
  ./prog_$cfg > out_$cfg.txt
  cmp -s out_$cfg.txt exp.txt || { echo "FAIL: output differs from the model ($cfg)"; diff out_$cfg.txt exp.txt; exit 1; }
  if [ $cfg = FULL ]; then
    # register form: rotates are rol/ror instructions (no shift pair left for them)
    grep -qE "\brol[bwlq] " .build/4_codegen.s && grep -qE "\bror[bwlq] " .build/4_codegen.s || { echo "FAIL: no rol/ror in the generated code"; exit 1; }
  fi
done
echo "PASS bits_rot_check: output equals the model in 3 configs, rol/ror emitted"
