# Independent model for bits_rot_test.caspien (generated by bits_rot_gen.py): rotate the bit pattern within the width, count modulo the width.
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bits_rot_gen import TYPES, values
M64 = (1 << 64) - 1

def rotl(x, k, w):
    k %= w
    m = (1 << w) - 1
    x &= m
    return ((x << k) | (x >> (w - k))) & m if k else x

def rotr(x, k, w):
    return rotl(x, -k % w, w)

for t, w, sg in TYPES:
    m = (1 << w) - 1
    for v in values(w, sg):
        x = v & m
        acc = 0
        def put(r):
            global acc
            acc = (acc * 1000003 + (r & m)) & M64
        for i in range(2 * w + 2):
            k = i & m          # wrap:<T>(i): the pattern of i at width w; a signed count is read modulo the width as well
            for r in (rotl(x, k, w), rotr(x, k, w), rotl(x, k, w), rotr(x, k, w)):
                put(r)
        counts = sorted({0, 1, 3, w - 1, w, w + 1, 2 * w + 3})
        if sg:
            counts += [-1, -3, -(w - 1), -w, -(w + 1)]
        for c in counts:
            put(rotl(x, c, w))
            put(rotr(x, c, w))
        print("%s %d %d" % (t, v, acc))
def s64(x):
    return x - (1 << 64) if x >> 63 else x
a = 81985529216486895
print("F %d %d %d %d %d %d %d" % (rotl(a, 12, 64), rotr(a, 12, 64), rotl(a, 76, 64), rotr(1, 1, 64), rotl(1, 64, 64), s64(rotl(-2, 1, 64)), s64(rotr(-2, 1, 64))))
