#!/usr/bin/env python3
"""Generates bits_rot_test.caspien (the bits_rotl / bits_rotr builtins at every integer width, signed and unsigned: runtime values through
@dont(inline) wrappers (stack form), inlined variable counts (register form, count in %cl), constant counts 0, 1, w-1, w, w+1 (and negative
ones for signed types: the count is taken modulo the width), constant-folded u64/s64 rotates). Expected output: bits_rot_test.py (an independent model)."""
import sys
TYPES = [("u8", 8, False), ("u16", 16, False), ("u32", 32, False), ("u64", 64, False),
         ("s8", 8, True), ("s16", 16, True), ("s32", 32, True), ("s64", 64, True)]

def values(w, signed):
    m = (1 << w) - 1
    pats = [0, 1, 2, m, m - 1, 1 << (w - 1), (0x5555555555555555 & m), (0xAAAAAAAAAAAAAAAA & m), (0x0F0F0F0F0F0F0F0F & m), (0x123456789ABCDEF1 & m), 3 & m, (m >> 1)]
    out = []
    for p in pats:
        if p not in out:
            out.append(p)
    return [(p - (1 << w)) if signed and p >> (w - 1) else p for p in out]

def src():
    L = []
    L.append("// GENERATED by bits_rot_gen.py -- do not edit. bits_rotl / bits_rotr at every width; output checked against bits_rot_test.py by bits_rot_check.sh.")
    L.append('import "../stdlib/libc.caspien"')
    L.append("")
    for t, w, sg in TYPES:
        u = ("u%d" % w) if sg else t
        conv = (lambda e: "wrap:<u64>(wrap:<%s>(%s))" % (u, e)) if sg else (lambda e: "wrap:<u64>(%s)" % e)
        L.append("@dont(inline)\nfunc rl_%s(x: mut %s, k: mut %s) mut %s{\n\treturn bits_rotl(x, k)\n}" % (t, t, t, t))
        L.append("@dont(inline)\nfunc rr_%s(x: mut %s, k: mut %s) mut %s{\n\treturn bits_rotr(x, k)\n}" % (t, t, t, t))
        L.append("@dont(inline)\nfunc run_%s(x: mut %s) mut u64{" % (t, t))
        L.append("\tlet acc = mut 0")
        L.append("\tlet lim = mut %d" % (2 * w + 2))
        L.append("\tfor i in 0..lim{")
        L.append("\t\tlet k = mut wrap:<%s>(i)" % t)
        for e in ("rl_%s(x, k)" % t, "rr_%s(x, k)" % t, "bits_rotl(x, k)", "bits_rotr(x, k)"):
            L.append("\t\tacc = acc * 1000003 + %s" % conv(e))
        L.append("\t}")
        counts = sorted({0, 1, 3, w - 1, w, w + 1, 2 * w + 3})
        if sg:
            counts += [-1, -3, -(w - 1), -w, -(w + 1)]
        for c in counts:
            for fn in ("bits_rotl", "bits_rotr"):
                L.append("\tacc = acc * 1000003 + %s" % conv("%s(x, %d)" % (fn, c)))
        L.append("\treturn acc\n}")
        L.append("")
    L.append("func main() void{")
    L.append("\tunsafe extern{")
    for t, w, sg in TYPES:
        for v in values(w, sg):
            L.append("\t\tlet:<mut %s> v_%s_%d = mut %d" % (t, t, abs(v) if v >= 0 else abs(v), v) if False else "\t\t{")
            L.pop()
            name = "v_%s_%s" % (t, ("m%d" % -v) if v < 0 else str(v))
            L.append("\t\tlet:<mut %s> %s = mut %d" % (t, name, v))
            L.append('\t\tprintf("%s %d %%llu\\n", run_%s(%s))' % (t, v, t, name))
    # constant-folded rotates (literal operands: u64 / s64 only, the literals' own types)
    L.append("\t\tlet:<mut u64> f1 = mut bits_rotl(81985529216486895, 12)")
    L.append("\t\tlet:<mut u64> f2 = mut bits_rotr(81985529216486895, 12)")
    L.append("\t\tlet:<mut u64> f3 = mut bits_rotl(81985529216486895, 76)")
    L.append("\t\tlet:<mut u64> f4 = mut bits_rotr(1, 1)")
    L.append("\t\tlet:<mut u64> f5 = mut bits_rotl(1, 64)")
    L.append("\t\tlet:<mut s64> f6 = mut bits_rotl(-2, 1)")
    L.append("\t\tlet:<mut s64> f7 = mut bits_rotr(-2, 1)")
    L.append('\t\tprintf("F %llu %llu %llu %llu %llu %lld %lld\\n", f1, f2, f3, f4, f5, f6, f7)')
    L.append("\t}")
    L.append("}")
    return "\n".join(L) + "\n"

if __name__ == "__main__":
    open(sys.argv[1] if len(sys.argv) > 1 else "bits_rot_test.caspien", "w").write(src())
