#!/usr/bin/env python3
"""Generates tests/fnv1a_test.caspien. Every expected value comes from the FNV-1a 64-bit reference below (and the three
published vectors are asserted here); none is typed by hand.   usage: python3 tests/fnv1a_gen.py > tests/fnv1a_test.caspien"""
import struct, sys

OFFSET, PRIME, M = 0xcbf29ce484222325, 0x100000001b3, 1 << 64


def fnv(bs):
    h = OFFSET
    for b in bs:
        h = ((h ^ b) * PRIME) % M
    return h


assert fnv(b"") == 0xcbf29ce484222325
assert fnv(b"a") == 0xaf63dc4c8601ec8c
assert fnv(b"foobar") == 0x85944171f73967e8

out = []
w = out.append
w('''// Tests for stdlib/hash.caspien: real 64-bit FNV-1a. `fnv1a64Bytes` against the published vectors and a Python reference over strings and
// byte patterns of every length class, and `hashOf:<T>` (copy the value's bytes, hash them) for u8 / u16 / u32 / u64 / s32 / s64 values
// against FNV-1a of the value's LITTLE-ENDIAN bytes. A struct cannot be passed to the generic `hashOf` (by-value struct parameter), so
// padding-free structs are hashed through `fnv1a64Bytes` on a copy of their bytes. Also: determinism, and distinct values hash differently.
// GENERATED by tests/fnv1a_gen.py -- every expected value is from that script's Python FNV-1a (the three published vectors
// "" -> 0xcbf29ce484222325, "a" -> 0xaf63dc4c8601ec8c, "foobar" -> 0x85944171f73967e8 are asserted there). Do not edit; edit the generator.
// Prints PASS/FAIL per check and a summary line; the output must be identical with every optimisation switch off and on.
import "../stdlib/libc.caspien"
import "../stdlib/hash.caspien"
import "../stdlib/gt_init.caspien"
import "../stdlib/gt_register.caspien"
import "../stdlib/gt_alive_check.caspien"
import "../stdlib/gt_destruct.caspien"
import "../stdlib/gt_moved.caspien"

let static passed = mut 0
let static failed = mut 0

@pub
struct Pair{@pub{
	a: mut u64
	b: mut u64
}}
@pub
struct Quad{@pub{
	a: mut u32
	b: mut u32
	c: mut u32
	d: mut u32
}}

func check(name: static imut string, ok: mut bool) void{
	unsafe{
		if ok{
			passed++
			printf("PASS %s\\n", name)
		}else{
			failed++
			printf("FAIL %s\\n", name)
		}
	}
	return
}
func checkHash(name: static imut string, got: mut u64, expected: mut u64) void{
	unsafe{
		if got == expected{
			passed++
			printf("PASS %s\\n", name)
		}else{
			failed++
			printf("FAIL %s expected %llx got %llx\\n", name, expected, got)
		}
	}
	return
}
// fnv1a64Bytes over the characters of a string literal (copied into a scratch buffer: a literal is not a `raw imut u8`)
func hashStr(s: static imut string) mut u64{
	let h = mut 0
	unsafe{
		let n = mut strlen(s)
		let buf = mut malloc(n + 1)
		memcopy(buf, n, s)
		h = fnv1a64Bytes(buf, n)
		free(buf)
	}
	return h
}
// fnv1a64Bytes over n bytes of the pattern byte(i) = (i * 37 + 11) mod 256
func hashPattern(n: mut u64) mut u64{
	let h = mut 0
	unsafe{
		let buf = mut malloc(n + 1)
		for i in 0..n{
			let v = mut wrap:<u8>(i * 37 + 11)
			memcopy(buf + i, mut 1, raw v)
		}
		h = fnv1a64Bytes(buf, n)
		free(buf)
	}
	return h
}
// the 16 member bytes of a struct (the hidden 8-byte class-id header in front of them is skipped); a struct local is copied
// out of the `auto` pointer first (`raw p` would be the address of the parameter, not of the struct)
func hashPair(p: auto imut Pair) mut u64{
	let h = mut 0
	unsafe{
		let n = mut sizeof(Pair)
		let buf = mut malloc(n)
		let c = imut deref(p)
		memcopy(buf, n, raw c)
		h = fnv1a64Bytes(buf + (n - 16), mut 16)
		free(buf)
	}
	return h
}
func hashQuad(p: auto imut Quad) mut u64{
	let h = mut 0
	unsafe{
		let n = mut sizeof(Quad)
		let buf = mut malloc(n)
		let c = imut deref(p)
		memcopy(buf, n, raw c)
		h = fnv1a64Bytes(buf + (n - 16), mut 16)
		free(buf)
	}
	return h
}

func main() void{
	// ---- published vectors (and a few more strings)
	checkHash("fnv1a64Bytes: empty", fnv1a64Bytes(null, mut 0), 0xcbf29ce484222325)
''')
for s in ["", "a", "foobar", "b", "ab", "abc", "hello", "hello world", "The quick brown fox jumps over the lazy dog", "0123456789abcdef"]:
    w('\tcheckHash("hashStr: %r", hashStr("%s"), %d)' % (s, s, fnv(s.encode())))
for n in [1, 2, 3, 7, 8, 9, 15, 16, 17, 31, 32, 33, 63, 64, 65, 100, 255, 256, 1000]:
    bs = bytes((i * 37 + 11) & 255 for i in range(n))
    w('\tcheckHash("hashPattern %d bytes", hashPattern(%d), %d)' % (n, n, fnv(bs)))
w('\t// ---- hashOf:<T> = FNV-1a of the value\'s little-endian bytes')
def ints(bits, signed):
    m = 1 << bits
    base = [0, 1, 2, 7, 42, 127, 128, 255, 256, 257, 65535, 65536, 0x01020304, 0x7fffffff, 0x80000000, 0xdeadbeef, 0xffffffff,
            0x0123456789abcdef, 0x7fffffffffffffff, 0x8000000000000000, 0xfedcba9876543210, 0xffffffffffffffff]
    vals = [v for v in base if v < m]
    if signed:
        vals = [v for v in vals if v < m // 2]
        vals += [m // 2 - 1] + [-1, -2, -128, -129, -255, -32768, -123456, -(m // 2)]
        vals = [v for v in vals if -(m // 2) <= v < m // 2]
    return sorted(set(vals))
w('''	let:<mut u8> v8 = mut 0
	let:<mut u16> v16 = mut 0
	let:<mut u32> v32 = mut 0
	let:<mut u64> v64 = mut 0
	let:<mut s32> t32 = mut 0
	let:<mut s64> t64 = mut 0''')
for tname, bits, signed in [("u8", 8, False), ("u16", 16, False), ("u32", 32, False), ("u64", 64, False), ("s32", 32, True), ("s64", 64, True)]:
    var = {"u8": "v8", "u16": "v16", "u32": "v32", "u64": "v64", "s32": "t32", "s64": "t64"}[tname]
    for v in ints(bits, signed):
        bs = (v % (1 << bits)).to_bytes(bits // 8, "little")
        lit = ("-%d" % -v) if v < 0 else str(v)
        w('\t%s = mut %s' % (var, lit))
        w('\tcheckHash("hashOf:<%s> %s", hashOf:<%s>(imut %s), %d)' % (tname, lit, tname, var, fnv(bs)))
w('''	// literal argument (adapts to T)
	checkHash("hashOf:<u64>(42) literal", hashOf:<u64>(imut 42), %d)
	checkHash("hashOf:<u32>(7) literal", hashOf:<u32>(imut 7), %d)
	checkHash("hashOf:<u8>(200) literal", hashOf:<u8>(imut 200), %d)''' % (fnv((42).to_bytes(8, 'little')), fnv((7).to_bytes(4, 'little')), fnv(bytes([200]))))
w('''	// ---- behaviour: deterministic, different inputs differ, width matters
	let a = mut hashOf:<u64>(imut 1234567)
	let b = mut hashOf:<u64>(imut 1234567)
	let c = mut hashOf:<u64>(imut 1234568)
	check("hashOf deterministic", a == b)
	check("hashOf: different values differ", a != c)
	check("hashOf: same value, different width differs", hashOf:<u32>(imut 7) != hashOf:<u64>(imut 7))''')
w('''	// ---- structs (padding-free), through fnv1a64Bytes over the member bytes
	let pr = mut Pair{a= mut 0x0102030405060708, b= mut 0x1112131415161718}
	let pr0 = mut Pair{a= mut 0, b= mut 0}
	let q = mut Quad{a= mut 1, b= mut 2, c= mut 0xdeadbeef, d= mut 0xffffffff}
''')
# the hidden header (if any) cannot be known here; the checks compare against FNV over the member bytes only when sizeof == member bytes
w('\tcheck("sizeof(Pair) == 24 (8-byte hidden header + 16 member bytes)", sizeof(Pair) == 24)')
w('\tcheck("sizeof(Quad) == 24 (8-byte hidden header + 16 member bytes)", sizeof(Quad) == 24)')
pb = struct.pack('<QQ', 0x0102030405060708, 0x1112131415161718)
p0 = bytes(16)
qb = struct.pack('<IIII', 1, 2, 0xdeadbeef, 0xffffffff)
w('\tcheckHash("hashPair {0x0102030405060708, 0x1112131415161718}", hashPair(auto pr), %d)' % fnv(pb))
w('\tcheckHash("hashPair {0, 0}", hashPair(auto pr0), %d)' % fnv(p0))
w('\tcheckHash("hashQuad {1, 2, 0xdeadbeef, 0xffffffff}", hashQuad(auto q), %d)' % fnv(qb))
w('''	unsafe{
		printf("fnv1a: %llu passed, %llu failed\\n", passed, failed)
		if failed == 0{
			printf("ALL FNV1A TESTS PASSED\\n")
		}
	}
}''')
sys.stdout.write("\n".join(l for l in out if l != '') .replace("\n\n\n", "\n\n") + "\n")
