#!/usr/bin/env python3
"""Generates div_fast_test.caspien: run-time (non-constant) unsigned division and modulo, u64 operands on both sides of the 2^32 boundary (the code takes a
32-bit divide when both operands are below 2^32) and u32/u16/u8 operands. Expected values come from Python integer arithmetic.
Run: python3 gen_div_fast.py > div_fast_test.caspien"""
A64 = [0, 1, 2, 7, 255, 65535, 4294967295, 4294967296, 4294967297, 1 << 40, (1 << 63) + 12345, (1 << 64) - 1]
B64 = [1, 2, 3, 10, 65536, 4294967295, 4294967296, 4294967311, (1 << 40) + 7, (1 << 64) - 1]
A32 = [0, 1, 255, 65535, 65536, 4294967294, 4294967295]
B32 = [1, 2, 3, 255, 65535, 65536, 4294967295]
A16 = [0, 1, 255, 256, 65535]
B16 = [1, 2, 255, 256, 65535]
A8 = [0, 1, 7, 128, 255]
B8 = [1, 2, 3, 16, 255]
out = ['''// GENERATED by gen_div_fast.py (expected values come from Python integer arithmetic). Run-time unsigned division and modulo: u64 operands on both
// sides of 2^32 (the generated code divides with divl when both are below 2^32 and divq otherwise), and u32 / u16 / u8 operands.
import "../stdlib/libc.caspien"
import "../stdlib/gt_init.caspien"
import "../stdlib/gt_register.caspien"
import "../stdlib/gt_alive_check.caspien"
import "../stdlib/gt_destruct.caspien"
import "../stdlib/gt_moved.caspien"

func check(name: static imut string, ok: imut bool) void{
	unsafe extern{
		if ok{ printf("PASS %s\\n", name) }
		else{ printf("FAIL %s\\n", name) }
	}
}
''']
for t in ['u64', 'u32', 'u16', 'u8']:
    out.append('''@dont(inline)
func dq%s(a: mut %s, b: mut %s) mut %s{
	match b != 0{
		return a / b
	}
	return 0
}

@dont(inline)
func dm%s(a: mut %s, b: mut %s) mut %s{
	match b != 0{
		return a %% b
	}
	return 0
}
''' % (t, t, t, t, t, t, t, t))
out.append('func main() void{')
for t, AS, BS in [('u64', A64, B64), ('u32', A32, B32), ('u16', A16, B16), ('u8', A8, B8)]:
    for i, a in enumerate(AS):
        for j, b in enumerate(BS):
            lit = (lambda v: str(v))
            if t == 'u64':
                va, vb = 'mut %d' % a, 'mut %d' % b
                out.append('\tcheck("%s_%d_%d", dq%s(%d, %d) == %d && dm%s(%d, %d) == %d)' % (t, i, j, t, a, b, a // b, t, a, b, a % b))
            else:
                out.append('\tcheck("%s_%d_%d", dq%s(wrap:<%s>(%d), wrap:<%s>(%d)) == %d && dm%s(wrap:<%s>(%d), wrap:<%s>(%d)) == %d)'
                           % (t, i, j, t, t, a, t, b, a // b, t, t, a, t, b, a % b))
out.append('}')
print('\n'.join(out))
