#!/usr/bin/env python3
"""Generates cmov_select_test.caspien: selects that ConditionalMovePass turns into R_CMOV (compare + cmov), for every integer type and all six
comparison operators: a one-arm `if c { r = i }`, a two-arm `if c { q = 11 } else { q = 0 }` (constant 0 must not clobber the flags), a big
64-bit immediate, clamps where the destination is also a compared operand, and a max/min of two variables. Expected values come from the Python
models below. Run: python3 gen_cmov_select.py > cmov_select_test.caspien"""
import operator
M = (1 << 64) - 1
OPS = [('EQ', '==', operator.eq), ('NEQ', '!=', operator.ne), ('LT', '<', operator.lt), ('LE', '<=', operator.le), ('GT', '>', operator.gt), ('GE', '>=', operator.ge)]
TYPES = {'u8': (8, False), 'u16': (16, False), 'u32': (32, False), 'u64': (64, False), 's8': (8, True), 's16': (16, True), 's32': (32, True), 's64': (64, True)}
PARAMS = {'u8': (37, 11, 29, 200), 'u16': (4099, 17, 2053, 60000), 'u32': (16777259, 5, 50331779, 9), 'u64': (1000000007, 3, 998244353, 77),
          's8': (37, 11, 29, 200), 's16': (4099, 17, 2053, 60000), 's32': (16777259, 5, 50331779, 9), 's64': (1000000007, 3, 998244353, 77)}
N = 300

def val(t, v):
    bits, signed = TYPES[t]
    v &= (1 << bits) - 1
    if signed and v >> (bits - 1):
        v -= 1 << bits
    return v

def model(t, cmp):
    m1, c1, m2, c2 = PARAMS[t]
    s = 0
    for i in range(N):
        x = val(t, i * m1 + c1); y = val(t, i * m2 + c2)
        r = i if cmp(x, y) else 100
        q = 11 if cmp(x, y) else 0
        w = (1 << 32) * 3 + 7 if cmp(x, 100) else 5
        s = (s + r + q * 3 + w) & M
    return s

def m_clamp(n):
    s = 0
    for i in range(n):
        v = (i * 7) % 23
        if v > 10: v = 10
        if v < 3: v = 3
        s += v
    return s

def m_maxmin(n):
    s = 0
    for i in range(n):
        a = (i * 31 + 5) % 97; b = (i * 17 + 40) % 89
        mx = a if a > b else b
        mn = b if a > b else a
        s += mx * 3 + mn
    return s

def m_narrowdst(n):
    s = 0
    for i in range(n):
        r = (i * 13) % 27
        ch = (97 + r) & 0xFF
        if r == 26: ch = 32
        s += ch
    return s

out = ['''// GENERATED by gen_cmov_select.py (expected values come from its Python models). Selects ConditionalMovePass turns into compare + cmov: one-arm and
// two-arm, constant / register / 64-bit immediate sources, every integer type and comparison, clamps, max/min, a narrow destination.
import "../stdlib/libc.caspien"
import "../stdlib/gt/*"

func check(name: static imut string, ok: imut bool) void{
	unsafe extern{
		if ok{ printf("PASS %s\\n", name) }
		else{ printf("FAIL %s\\n", name) }
	}
}
''']
checks = []
for t in TYPES:
    m1, c1, m2, c2 = PARAMS[t]
    for (nm, sym, fn) in OPS:
        name = 'sel_%s_%s' % (t, nm)
        out.append('''@dont(inline)
func %s(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		let:<mut %s> x = mut wrap:<%s>(i * %d + %d)
		let:<mut %s> y = mut wrap:<%s>(i * %d + %d)
		let r = mut 100
		if x %s y{ r = i }
		let q = mut 0
		if x %s y{
			q = 11
		}
		else{
			q = 0
		}
		let w = mut 5
		if x %s 100{ w = 12884901895 }
		s = s + r + q * 3 + w
	}
	return s
}
''' % (name, t, t, m1, c1, t, t, m2, c2, sym, sym, sym))
        checks.append('\tcheck("%s", %s(%d) == %d)' % (name, name, N, model(t, fn)))
out.append('''@dont(inline)
func clamp(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		let v = mut ((i * 7) % 23)
		if v > 10{ v = 10 }
		if v < 3{ v = 3 }
		s = s + v
	}
	return s
}

@dont(inline)
func maxmin(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		let a = mut ((i * 31 + 5) % 97)
		let b = mut ((i * 17 + 40) % 89)
		let mx = mut 0
		let mn = mut 0
		if a > b{
			mx = a
		}
		else{
			mx = b
		}
		if a > b{
			mn = b
		}
		else{
			mn = a
		}
		s = s + mx * 3 + mn
	}
	return s
}

@dont(inline)
func narrowdst(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		let r = mut ((i * 13) % 27)
		let:<mut u8> ch = mut wrap:<u8>(97 + r)
		if r == 26{
			ch = 32
		}
		s = s + wrap:<u64>(ch)
	}
	return s
}
''')
for n in [0, 1, 27, 300]:
    checks.append('\tcheck("clamp_%d", clamp(%d) == %d)' % (n, n, m_clamp(n)))
    checks.append('\tcheck("maxmin_%d", maxmin(%d) == %d)' % (n, n, m_maxmin(n)))
    checks.append('\tcheck("narrowdst_%d", narrowdst(%d) == %d)' % (n, n, m_narrowdst(n)))
out.append('func main() void{')
out += checks
out.append('}')
print('\n'.join(out))
