#!/usr/bin/env python3
"""Generates nested_unroll_test.caspien: loop nests whose OUTER loop is fully unrolled with the loop variable replaced by a literal
(`loop-unroll-nested: on`). Every expected value is computed here by a Python model of the same loops."""
out = []
w = out.append
w("// GENERATED by gen_nested_unroll.py -- do not edit. Loop nests (rectangular, triangular, three deep, inner bound from the outer variable incl. an empty")
w("// range, indexed array access, a nest with break). Results must be identical with loop-unroll-nested on or off, and with any unrolling preset.")
w('import "../stdlib/libc.caspien"')
w('import "../stdlib/gt_init.caspien"\nimport "../stdlib/gt_register.caspien"\nimport "../stdlib/gt_alive_check.caspien"\nimport "../stdlib/gt_destruct.caspien"\nimport "../stdlib/gt_moved.caspien"')
w("""
func check(name: static imut string, got: mut u64, want: mut u64) void{
	unsafe extern{
		if got == want{
			printf("PASS %s\\n", name)
		}else{
			printf("FAIL %s got %llu want %llu\\n", name, got, want)
		}
	}
	return
}
""")
funcs = []   # (name, body lines, expected)
def F(name, body, want): funcs.append((name, body, want))

F("rect", ["let s = mut 0", "for i in 0..4{", "\tfor j in 0..3{", "\t\ts = s + i * 10 + j", "\t}", "}", "return s"],
  sum(i * 10 + j for i in range(4) for j in range(3)))
F("tri", ["let s = mut 0", "for i in 0..5{", "\tlet j0 = mut (i + 1)", "\tfor j in j0..5{", "\t\ts = s + i * j", "\t}", "}", "return s"],
  sum(i * j for i in range(5) for j in range(i + 1, 5)))
F("three", ["let s = mut 0", "for i in 0..3{", "\tfor j in 0..3{", "\t\tfor k in 0..3{", "\t\t\ts = s + i * 100 + j * 10 + k", "\t\t}", "\t}", "}", "return s"],
  sum(i * 100 + j * 10 + k for i in range(3) for j in range(3) for k in range(3)))
F("innerbound", ["let s = mut 0", "for i in 0..5{", "\tfor j in 0..i{", "\t\ts = s + j + 7 * i", "\t}", "}", "return s"],
  sum(j + 7 * i for i in range(5) for j in range(i)))
F("innerend", ["let s = mut 0", "for i in 0..4{", "\tlet e = mut (i + 2)", "\tfor j in i..e{", "\t\ts = s + (j + 1) * (i + 3)", "\t}", "}", "return s"],
  sum((j + 1) * (i + 3) for i in range(4) for j in range(i, i + 2)))
F("condition", ["let s = mut 0", "for i in 0..6{", "\tfor j in 0..6{", "\t\tif i < j{", "\t\t\ts = s + i * j", "\t\t}else{", "\t\t\ts = s + 1", "\t\t}", "\t}", "}", "return s"],
  sum(i * j if i < j else 1 for i in range(6) for j in range(6)))
F("breaks", ["let s = mut 0", "for i in 0..5{", "\tfor j in 0..5{", "\t\tif j > i{", "\t\t\tbreak", "\t\t}", "\t\ts = s + i + j", "\t}", "}", "return s"],
  sum(i + j for i in range(5) for j in range(5) if not any(jj > i for jj in range(j + 1)) ))
# indexed array through an unsafe dynarray: a[i] * a[j] over the triangle
vals = [3, 1, 4, 1, 5, 9, 2, 6]
F("indexed", ["unsafe udyn{", "\tlet a = mut unsafe dyn:<u64>([])", "\ta = resize(a, 8)"] +
  [f"\ta[{k}] = {v}" for k, v in enumerate(vals)] +
  ["\tlet s = mut 0", "\tfor i in 0..8{", "\t\tlet j0 = mut (i + 1)", "\t\tfor j in j0..8{", "\t\t\ts = s + a[i] * a[j]", "\t\t}", "\t}", "\treturn s", "}"],
  sum(vals[i] * vals[j] for i in range(8) for j in range(i + 1, 8)))
for name, body, want in funcs:
    w(f"func {name}() mut u64{{")
    for l in body: w("\t" + l)
    w("}\n")
w("func main() void{")
for name, body, want in funcs: w(f'\tcheck("{name}", {name}(), {want})')
w("\treturn\n}")
open("nested_unroll_test.caspien", "w").write("\n".join(out) + "\n")
print("checks:", len(funcs))
