#!/usr/bin/env python3
"""Generates mul_const_test.caspien and mul_const_test.py (independent model). Multiplication by constants: powers of two, 3/5/9 (lea),
2^n+1 and 2^n-1 (shift and add/sub) and other constants (imul), on u64, s64 and u32 values (wrapping)."""
M64 = (1 << 64) - 1
KS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 16, 17, 31, 32, 33, 63, 64, 65, 127, 129, 1000, 4096, 65535, 65537, 1664525, 2147483647, 2147483648, 4294967295, 16777217]
def s64(v):
    v &= M64
    return v - (1 << 64) if v >> 63 else v
L = ['''// Multiplication by a constant in register form: Codegen's rfMulByConst turns k = 2^n into shl, 3/5/9 into lea, 2^n+1 and 2^n-1 into
// shift and add/sub and keeps imul for the rest. u64, s64 and u32 operands (wrapping products), many constants. GENERATED by gen_mul_const.py;
// expected output in mul_const_test.py (independent Python model).
import "../stdlib/libc.caspien"
import "../stdlib/gt/*"
''']
model = []
for K in KS:
    L.append('@dont(inline)\nfunc k%d() void{' % K)
    L.append('\tlet a = mut 0\n\tlet:<mut s64> b = mut 0\n\tlet:<mut u32> c = mut 0')
    L.append('\tfor i in 0..200{')
    L.append('\t\tlet x = mut (i * 1099511628211 + 14695981039346656037)')
    L.append('\t\tlet:<mut s64> y = mut (wrap:<s64>(i * 7919) - 100000)')
    L.append('\t\tlet:<mut u32> w = mut wrap:<u32>(i * 40503 + 99)')
    L.append('\t\ta = a + x * %d' % K)
    L.append('\t\tb = b + y * %d' % K)
    L.append('\t\tc = c + w * %d' % K)
    L.append('\t}')
    L.append('\tunsafe extern{ printf("%d %%llu %%lld %%llu\\n", a, b, c as u64) }' % K)
    L.append('}')
    a = b = c = 0
    for i in range(200):
        x = (i * 1099511628211 + 14695981039346656037) & M64
        y = i * 7919 - 100000
        w = (i * 40503 + 99) & 0xFFFFFFFF
        a = (a + x * K) & M64
        b = s64(b + y * K)
        c = (c + w * K) & 0xFFFFFFFF
    model.append("%d %d %d %d" % (K, a, b, c))
L.append("func main() void{\n" + "\n".join("\tk%d()" % K for K in KS) + "\n}\n")
open("mul_const_test.caspien", "w").write("\n".join(L))
open("mul_const_test.py", "w").write("#!/usr/bin/env python3\n# Independent model for mul_const_test.caspien (generated by gen_mul_const.py)\n" + "".join('print("%s")\n' % m for m in model))
