#!/usr/bin/env python3
"""Generates stride_index_test.caspien: struct-element access at a RUN-TIME index with element sizes that are not 1/2/4/8
(`R_LEA .. stride` + `R_LD/R_ST/R_LDX/R_STX` fused into `R_LDI/R_STI/R_LDXI/R_STXI`, the index multiplied into the scratch register), on unsafe and
safe dynarrays: every field written, the last field overwritten, everything summed. Structs are @untyped and homogeneous (stride = fields * width).
Expected values come from the Python model below (small values, no overflow)."""
MASK = {"u8": 255, "u16": 65535, "u32": 2**32 - 1, "u64": 2**64 - 1}
SHAPES = [("u8", 3), ("u8", 5), ("u16", 3), ("u16", 7), ("u32", 3), ("u32", 5), ("u64", 3), ("u64", 7),
          ("f32", 3), ("f32", 5), ("f64", 3), ("f64", 5), ("f64", 7)]
N = 9
out = []
w = out.append
w("// GENERATED by gen_stride_index.py -- do not edit. Struct-element access at a run-time index, strides that are not 1/2/4/8, unsafe and safe dynarrays.")
w('import "../stdlib/libc.caspien"\nimport "../stdlib/gt/*"')
w("""
func check(name: static imut string, got: mut u64, want: mut u64) void{
	unsafe extern{
		if got == want{
			printf("PASS %s\\n", name)
		}else{
			printf("FAIL %s got %llu want %llu\\n", name, got, want)
		}
	}
	return
}

func checkf32(name: static imut string, got: mut f32, want: mut f32) void{
	unsafe assume extern{
		assume match got : finite
		assume match want : finite
		if got == want{
			printf("PASS %s\\n", name)
		}else{
			printf("FAIL %s\\n", name)
		}
	}
	return
}

func checkf64(name: static imut string, got: mut f64, want: mut f64) void{
	unsafe assume extern{
		assume match got : finite
		assume match want : finite
		if got == want{
			printf("PASS %s\\n", name)
		}else{
			printf("FAIL %s\\n", name)
		}
	}
	return
}
""")
mains = []
for t, nf in SHAPES:
    S = f"S_{t}_{nf}"
    isf = t.startswith("f")
    w("@untyped\nstruct %s{@pub{\n%s}}\n" % (S, "".join(f"\ta{f}: mut {t}\n" for f in range(nf))))
    if isf:
        vals = [[(i + 1.0) * (f + 1) for f in range(nf)] for i in range(N)]
        for i in range(N): vals[i][nf - 1] = (i + 1.0) + 100.0
        want = sum(vals[i][f] * (f + 1) for i in range(N) for f in range(nf))
    else:
        vals = [[(i * 37 + f * 11 + 5) & MASK[t] for f in range(nf)] for i in range(N)]
        for i in range(N): vals[i][nf - 1] = (i * 5 + 3) & MASK[t]
        want = sum(vals[i][f] * (f + 1) for i in range(N) for f in range(nf))
    CONST = [(2, 0, 1), (7, nf - 1, 3), (5, 1, 7)]   # (element, field, multiplier) read at LITERAL indexes after the loops
    want += sum(vals[e][f] * m for e, f, m in CONST)
    for mode in ("udyn", "safe"):
        fn = f"{S}_{mode}"
        rt = t if isf else "u64"
        w(f"@dont(inline)\nfunc {fn}(n: mut u64) mut {rt}{{")
        if mode == "safe":
            w("\t?catch(e){ return 0" + (".0" if isf else "") + " }")
        blk = {"udyn": ("unsafe assume udyn" if isf else "unsafe udyn"), "safe": ("unsafe assume" if isf else None)}[mode]
        ind = "\t"
        if blk:
            w(f"\t{blk}{{"); ind = "\t\t"
        if mode == "udyn":
            w(f"{ind}let d = mut unsafe dyn:<{S}>([])\n{ind}d = resize(d, n)")
        else:
            z = ", ".join(f"a{f}= 0" + (".0" if isf else "") for f in range(nf))
            w(f"{ind}let zero = mut {S}{{{z}}}\n{ind}let d = mut ? dyn:<{S}>([])\n{ind}d = ? resize(d, n, zero)")
        def loop(kind, lines):  # kind 'w' (write) or 'r' (read) -> proof wrapper for the safe form
            w(f"{ind}@dont(unroll)\n{ind}for i in 0..n{{")
            pre = ""
            if isf: w(f"{ind}\tassume match fi : finite\n{ind}\tfi = fi + 1.0\n{ind}\tassume match fi : finite")
            if mode == "safe":
                w(f"{ind}\tmatch i {'into' if kind == 'w' else 'in'} d{{")
                pre = "\t"
            for l in lines: w(f"{ind}\t{pre}{l}")
            if mode == "safe": w(f"{ind}\t}}")
            w(f"{ind}}}")
        # phase 1: every field
        if isf: w(f"{ind}let:<mut {t}> fi = mut 0.0")
        if isf:
            loop("w", [x for f in range(nf) for x in (f"assume match fi*{f + 1}.0 : finite", f"d[i].a{f} = fi * {f + 1}.0")])
        else:
            loop("w", [f"d[i].a{f} = " + (f"wrap:<{t}>(i * 37 + {f * 11 + 5})" if t != "u64" else f"i * 37 + {f * 11 + 5}") for f in range(nf)])
        # phase 2: overwrite the last field
        if isf:
            w(f"{ind}let:<mut {t}> fj = mut 0.0")
            w(f"{ind}@dont(unroll)\n{ind}for i in 0..n{{")
            w(f"{ind}\tassume match fj : finite\n{ind}\tfj = fj + 1.0\n{ind}\tassume match fj : finite")
            if mode == "safe": w(f"{ind}\tmatch i into d{{")
            p = "\t" if mode == "safe" else ""
            w(f"{ind}\t{p}assume match fj+100.0 : finite\n{ind}\t{p}d[i].a{nf - 1} = fj + 100.0")
            if mode == "safe": w(f"{ind}\t}}")
            w(f"{ind}}}")
        else:
            loop("w", [f"d[i].a{nf - 1} = " + (f"wrap:<{t}>(i * 5 + 3)" if t != "u64" else "i * 5 + 3")])
        w((f"{ind}let:<mut {t}> s = mut 0.0") if isf else f"{ind}let s = mut 0")
        if isf:
            lines = []
            for f in range(nf):
                lines += [f"assume match d[i].a{f} : finite", f"assume match d[i].a{f}*{f + 1}.0 : finite", f"assume match s : finite", f"s = s + d[i].a{f} * {f + 1}.0"]
            # no float counter needed in the sum loop: use a plain loop
            w(f"{ind}@dont(unroll)\n{ind}for i in 0..n{{")
            if mode == "safe": w(f"{ind}\tmatch i in d{{")
            p = "\t" if mode == "safe" else ""
            for l in lines: w(f"{ind}\t{p}{l}")
            if mode == "safe": w(f"{ind}\t}}")
            w(f"{ind}}}")
        else:
            w(f"{ind}@dont(unroll)\n{ind}for i in 0..n{{")
            if mode == "safe": w(f"{ind}\tmatch i in d{{")
            p = "\t" if mode == "safe" else ""
            for f in range(nf): w(f"{ind}\t{p}s = s + (d[i].a{f} as u64) * {f + 1}" if t != "u64" else f"{ind}\t{p}s = s + d[i].a{f} * {f + 1}")
            if mode == "safe": w(f"{ind}\t}}")
            w(f"{ind}}}")
        # literal-index reads (immediate index * stride + field offset folded into one displacement); the safe form needs a proof per literal
        cind = ind
        if mode == "safe":
            for e in sorted({e for e, f, m in CONST}):
                w(f"{cind}match {e} in d{{"); cind += "\t"
        for e, f, m in CONST:
            if isf:
                w(f"{cind}assume match d[{e}].a{f} : finite\n{cind}assume match d[{e}].a{f}*{m}.0 : finite\n{cind}assume match s : finite\n{cind}s = s + d[{e}].a{f} * {m}.0")
            else:
                w(f"{cind}s = s + " + (f"(d[{e}].a{f} as u64) * {m}" if t != "u64" else f"d[{e}].a{f} * {m}"))
        if mode == "safe":
            for _ in sorted({e for e, f, m in CONST}):
                cind = cind[:-1]; w(f"{cind}}}")
        w(f"{ind}return s")
        if blk: w("\t}")
        w("}\n")
        mains.append(f'\tcheck{"f" + t[1:] if isf else ""}("{fn}", {fn}({N}), {float(want) if isf else int(want)})')
w("func main() void{")
w("\n".join(mains))
w("\treturn\n}")
open("stride_index_test.caspien", "w").write("\n".join(out) + "\n")
print("checks:", len(mains))
