#!/usr/bin/env python3
"""Generates narrow_branch_test.caspien and narrow_branch_test.py (the independent model) -- run once, both files are checked in.
Compare-and-branch of 1/2/4 byte values (BranchFusionPass narrow R_BRC): variable against constant (either side), variable against
variable, all six operators, unsigned and signed types, values around every boundary, plus unmasked narrow arithmetic as an operand."""
import itertools
OPS = [("==", lambda a, b: a == b), ("!=", lambda a, b: a != b), ("<", lambda a, b: a < b), ("<=", lambda a, b: a <= b),
       (">", lambda a, b: a > b), (">=", lambda a, b: a >= b)]
TYPES = [("u8", 8, False), ("u16", 16, False), ("u32", 32, False), ("s8", 8, True), ("s16", 16, True), ("s32", 32, True)]
def wrap(v, bits, signed):
    v &= (1 << bits) - 1
    return v - (1 << bits) if signed and v >= (1 << (bits - 1)) else v
caspien = ['''// Compare-and-branch of narrow (1, 2, 4 byte) values: BranchFusionPass fuses `R_BIN cmp n ; R_BRF` into a sized `cmpb/cmpw/cmpl` + jump for register and
// immediate operands. Every type u8 u16 u32 s8 s16 s32, all six operators, variable vs constant (on either side), variable vs variable, and a
// narrow arithmetic result (x + c, which is not masked in its register) as an operand. Values sweep the boundaries. GENERATED by gen_narrow_branch.py;
// expected output in narrow_branch_test.py (an independent Python model). Prints one line per type and kind with the counts of true compares.
import "../stdlib/libc.caspien"
import "../stdlib/gt/*"
''']
model = []
STEP = {8: 1, 16: 257, 32: 16777259}
N = {8: 520, 16: 700, 32: 700}
for name, bits, signed in TYPES:
    K1 = {8: 100, 16: 30000, 32: 3000000000}[bits] if not signed else {8: -3, 16: -300, 32: -70000}[bits]
    K2 = {8: 200, 16: 65535, 32: 4294967295}[bits] if not signed else {8: 127, 16: 32767, 32: 2147483647}[bits]
    cs = lambda k: str(k)
    # runtime sequences: x_i = wrap(i*S), y_i = wrap(i*S2 + 5)
    S, S2 = STEP[bits], STEP[bits] * 3 + 2
    n = N[bits]
    f = "run_%s" % name
    L = ['@dont(inline)', 'func %s() void{' % f]
    L.append('\tlet cnt = mut [%s]' % ", ".join(["0"] * (6 * 5)))
    L.append('\tfor i in 0..%d{' % n)
    L.append('\t\tlet:<mut %s> x = mut wrap:<%s>(i * %d)' % (name, name, S))
    L.append('\t\tlet:<mut %s> y = mut wrap:<%s>(i * %d + 5)' % (name, name, S2))
    L.append('\t\tlet:<mut %s> z = mut wrap:<%s>(i * %d + 7)' % (name, name, S))
    idx = 0
    cnts = [0] * 30
    for oi, (op, fn) in enumerate(OPS):
        for kind in range(5):
            if kind == 0: cond = "x %s %s" % (op, cs(K1))
            elif kind == 1: cond = "%s %s x" % (cs(K2), op)
            elif kind == 2: cond = "x %s y" % op
            elif kind == 3: cond = "x %s %s" % (op, cs(K2))
            else: cond = "x + 1 %s z" % op  # x + 1 wraps in the narrow type (value in an unmasked register)
            L.append('\t\tif %s{' % cond)
            L.append('\t\t\tcnt[%d] += 1' % (oi * 5 + kind))
            L.append('\t\t}')
    L.append('\t}')
    # print counts
    L.append('\tunsafe extern{')
    L.append('\t\tprintf("%s %s\\n", %s)' % (name, " ".join(["%llu"] * 30), ", ".join("cnt[%d]" % i for i in range(30))))
    L.append('\t}')
    L.append('}')
    caspien.append("\n".join(L) + "\n")
    # model
    out = [0] * 30
    for i in range(n):
        x = wrap(i * S, bits, signed); y = wrap(i * S2 + 5, bits, signed); z = wrap(i * S + 7, bits, signed)
        for oi, (op, fn) in enumerate(OPS):
            vals = [fn(x, K1), fn(K2, x), fn(x, y), fn(x, K2), fn(wrap(x + 1, bits, signed), z)]
            for kind, v in enumerate(vals):
                if v: out[oi * 5 + kind] += 1
    model.append("%s %s" % (name, " ".join(map(str, out))))
caspien.append("func main() void{\n" + "\n".join("\t%s()" % ("run_" + t[0]) for t in TYPES) + "\n}\n")
open("narrow_branch_test.caspien", "w").write("\n".join(caspien))
open("narrow_branch_test.py", "w").write("#!/usr/bin/env python3\n# Independent model for narrow_branch_test.caspien (generated by gen_narrow_branch.py)\n" + "".join('print("%s")\n' % m for m in model))
