#!/usr/bin/env python3
"""Generates static_aggregate_test.caspien: initialised `let static` aggregates -- arrays of structs, structs holding structs, arrays of those.
Before the fix the Codegen aliased "a.0" into "a" but not "a.0.x" into "a", so the array was emitted as zeros and every read gave 0.
Every expected value comes from the Python lists below (the model is the literal data plus the writes)."""
import random
random.seed(11)
out = []
w = out.append
w("// GENERATED by gen_static_aggregate.py -- do not edit. Initialised static arrays of structs / nested structs: reads, then writes, then reads.")
w('import "../stdlib/libc.caspien"')
w("""
@untyped
struct Mix{@pub{
	a: mut u64
	b: mut u8
	c: mut u32
	d: mut f64
}}
@untyped
struct Inner{@pub{
	p: mut u16
	q: mut f64
}}
@untyped
struct Outer{@pub{
	i: mut Inner
	t: mut u64
}}

func check(name: static imut string, ok: mut bool) void{
	unsafe extern{
		if ok{ printf("PASS %s\\n", name) } else { printf("FAIL %s\\n", name) }
	}
}
""")
mix = [dict(a=random.randrange(1 << 40), b=random.randrange(256), c=random.randrange(1 << 32), d=random.randrange(-64, 64) / 4) for _ in range(4)]
outer = [dict(p=random.randrange(65536), q=random.randrange(-64, 64) / 4, t=random.randrange(1 << 40)) for _ in range(3)]
single = dict(p=random.randrange(65536), q=random.randrange(-64, 64) / 4, t=random.randrange(1 << 40))
f = lambda v: repr(float(v))
w("let static:<mut Mix[4]> mx = mut [" + ", ".join(f"Mix{{a= {m['a']}, b= {m['b']}, c= {m['c']}, d= {f(m['d'])}}}" for m in mix) + "]")
w("let static:<mut Outer[3]> ou = mut [" + ", ".join(f"Outer{{i= Inner{{p= {o['p']}, q= {f(o['q'])}}}, t= {o['t']}}}" for o in outer) + "]")
w(f"let static:<mut Outer> one = mut Outer{{i= Inner{{p= {single['p']}, q= {f(single['q'])}}}, t= {single['t']}}}")
w("\nfunc main() void{\n\tunsafe assume global{")
n = 0
def chk(expr, want, ty):
    global n
    n += 1
    if isinstance(want, str) and '.' in want:
        w(f'\t\tassume match {expr} : finite')
    w(f'\t\tcheck("{expr}", {expr} == {want})')
for k, m in enumerate(mix):
    for fld in "abcd":
        chk(f"mx[{k}].{fld}", f(m[fld]) if fld == "d" else m[fld], None)
for k, o in enumerate(outer):
    chk(f"ou[{k}].i.p", o["p"], None); chk(f"ou[{k}].i.q", f(o["q"]), None); chk(f"ou[{k}].t", o["t"], None)
chk("one.i.p", single["p"], None); chk("one.i.q", f(single["q"]), None); chk("one.t", single["t"], None)
# writes, then reads back (model: apply the same writes to the lists)
mix[2]["a"] = 123456789012; mix[2]["d"] = -7.5
w("\t\tmx[2].a = 123456789012\n\t\tmx[2].d = -7.5")
w("\t\tou[1].i.p = 4242\n\t\tou[1].i.q = 0.125")
outer[1]["p"] = 4242; outer[1]["q"] = 0.125
chk("mx[2].a", mix[2]["a"], None); chk("mx[2].d", f(mix[2]["d"]), None); chk("mx[1].c", mix[1]["c"], None)
chk("ou[1].i.p", 4242, None); chk("ou[1].i.q", "0.125", None); chk("ou[1].t", outer[1]["t"], None); chk("ou[0].i.p", outer[0]["p"], None)
# sum over a loop with a proven variable index
sa = sum(m["a"] for m in mix) & (2**64 - 1)
w("\t\tlet s = mut 0\n\t\tfor i in mx{\n\t\t\tmatch i in mx{\n\t\t\t\ts = s + mx[i].a\n\t\t\t}\n\t\t}")
chk("s", sa, None)
w("\t}\n\treturn\n}")
open("static_aggregate_test.caspien", "w").write("\n".join(out) + "\n")
print("checks:", n)
