#!/usr/bin/env python3
"""Generates loop_rotation_test.caspien. Every case is a loop shape LoopRotationPass may rotate (for / unsafe loop with an exit test first,
with continue, break, return, narrow and signed counters, run-time and zero-trip bounds, a dynarray length bound) and the expected values come from
the plain Python models below, not from the compiler. Run: python3 gen_loop_rotation.py > loop_rotation_test.caspien"""

def m_forsum(n): return sum(i * i + 1 for i in range(n))
def m_tri(n): return sum(j + 1 for i in range(n) for j in range(i))
def m_cont(n): return sum(i for i in range(n) if i % 3 != 0)
def m_brk(n):
    for i in range(1000):
        if i * i > n: return i
    return 0
def m_while(n):
    i = 0; s = 0
    while i < n:
        s += 2 * i + 1; i += 1
    return s
def m_down(k):
    s = 0
    while k != 0:
        s += k; k -= 1
    return s
def m_u8(lim):
    c = 0; cnt = 0
    while c < lim:
        cnt += 3; c = (c + 1) & 255
    return cnt
def m_s64(start):
    x = start; n = 0
    while x > -5:
        x -= 1; n += 1
    return n
def m_find(n, t):
    for i in range(n):
        if i * 7 % 11 == t: return i
    return 9999
def m_nest(n):
    s = 0
    for i in range(n):
        for j in range(n):
            if j == i: continue
            if j > 5: break
            s += 10 * i + j
    return s
def m_big(n): return sum(i % 7 for i in range(n))
def m_dyn(vals):
    return sum(v * 3 for v in vals)

CASES = []
def case(name, args, call, expected): CASES.append((name, args, call, expected))

out = []
out.append('''// GENERATED by gen_loop_rotation.py (expected values come from its Python models). Loop shapes that LoopRotationPass copies the exit test of:
// for loops with literal and run-time bounds (including zero trips), nested loops, continue / break / return inside, `unsafe loop` with the exit test
// first (unsigned, narrow u8 and signed counters), a safe dynarray length as the bound. Each line checks the result against the model.
import "../stdlib/libc.caspien"
import "../stdlib/gt/*"

func check(name: static imut string, ok: imut bool) void{
	unsafe extern{
		if ok{ printf("PASS %s\\n", name) }
		else{ printf("FAIL %s\\n", name) }
	}
}

@dont(inline)
func forsum(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		s += i * i + 1
	}
	return s
}

@dont(inline)
func tri(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		for j in 0..i{
			s += j + 1
		}
	}
	return s
}

@dont(inline)
func cont(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		if i % 3 == 0{ continue }
		s += i
	}
	return s
}

@dont(inline)
func brk(n: mut u64) mut u64{
	let r = mut 0
	for i in 0..1000{
		if i * i > n{
			r = i
			break
		}
	}
	return r
}

@dont(inline)
func whileLoop(n: mut u64) mut u64{
	let i = mut 0
	let s = mut 0
	unsafe loop{
		loop{
		if i >= n{ break }
		s += 2 * i + 1
		i += 1
		}
	}
	return s
}

@dont(inline)
func down(k0: mut u64) mut u64{
	let k = mut k0
	let s = mut 0
	unsafe loop{
		loop{
		if k == 0{ break }
		s += k
		k -= 1
		}
	}
	return s
}

@dont(inline)
func narrow(lim: mut u8) mut u64{
	let:<mut u8> c = mut 0
	let cnt = mut 0
	unsafe loop{
		loop{
		if c >= lim{ break }
		cnt += 3
		c = wrap:<u8>(c + 1)
		}
	}
	return cnt
}

@dont(inline)
func signed(start: mut s64) mut u64{
	let x = mut start
	let n = mut 0
	unsafe loop{
		loop{
		if x <= -5{ break }
		x -= 1
		n += 1
		}
	}
	return n
}

@dont(inline)
func find(n: mut u64, t: mut u64) mut u64{
	for i in 0..n{
		if i * 7 % 11 == t{ return i }
	}
	return 9999
}

@dont(inline)
func nest(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		for j in 0..n{
			if j == i{ continue }
			if j > 5{ break }
			s += 10 * i + j
		}
	}
	return s
}

@dont(inline)
func big(n: mut u64) mut u64{
	let s = mut 0
	for i in 0..n{
		s += i % 7
	}
	return s
}

@dont(inline)
func dynsum(m: mut u64) mut u64{
	?catch(e){ return 7777777 }
	let d = mut ? dyn([3, 1, 4, 1, 5, 9, 2, 6])
	let s = mut 0
	let i = mut 0
	unsafe loop{
		loop{
		if i >= m{ break }
		match i in d{
			s += d[i] * 3
		}
		i += 1
		}
	}
	return s
}

func main() void{''')

def emit(name, call, exp):
    out.append('\tcheck("%s", %s == %d)' % (name, call, exp))

for n in (0, 1, 2, 7, 100): emit('for sum n=%d' % n, 'forsum(%d)' % n, m_forsum(n))
for n in (0, 1, 2, 9, 40): emit('triangular n=%d' % n, 'tri(%d)' % n, m_tri(n))
for n in (0, 1, 3, 10, 61): emit('for continue n=%d' % n, 'cont(%d)' % n, m_cont(n))
for n in (0, 1, 2, 50, 998001): emit('for break n=%d' % n, 'brk(%d)' % n, m_brk(n))
for n in (0, 1, 2, 50): emit('while-style n=%d' % n, 'whileLoop(%d)' % n, m_while(n))
for k in (0, 1, 10, 1000): emit('countdown k=%d' % k, 'down(%d)' % k, m_down(k))
for lim in (0, 1, 2, 100, 255): emit('u8 counter lim=%d' % lim, 'narrow(%d)' % lim, m_u8(lim))
for s in (10, 0, -4, -5, -9): emit('signed counter start=%d' % s, 'signed(%d)' % s, m_s64(s))
for n, t in ((0, 3), (1, 0), (20, 3), (20, 10), (5, 10)): emit('return inside n=%d t=%d' % (n, t), 'find(%d, %d)' % (n, t), m_find(n, t))
for n in (0, 1, 2, 8, 9): emit('nested continue/break n=%d' % n, 'nest(%d)' % n, m_nest(n))
for n in (0, 1, 3000000): emit('large trip count n=%d' % n, 'big(%d)' % n, m_big(n))
vals = [3, 1, 4, 1, 5, 9, 2, 6]
for m in (0, 1, 5, 8): emit('dynarray bound m=%d' % m, 'dynsum(%d)' % m, m_dyn(vals[:m]))
out.append('}')
print('\n'.join(out))
