#!/usr/bin/env python3
"""Generates div_narrow_test.caspien: u8 / u16 / u32 values (run-time, around the type limits) divided and reduced by literal divisors that are not powers
of two (the reciprocal-multiplication path of R_DIVC, now also for narrow types). Expected values come from Python integer arithmetic.
Run: python3 gen_div_narrow.py > div_narrow_test.caspien"""
T = {
    'u8': (255, [3, 5, 7, 10, 100, 255], [0, 1, 2, 3, 99, 100, 101, 127, 128, 200, 254, 255]),
    'u16': (65535, [3, 7, 10, 641, 1000, 65535], [0, 1, 2, 9, 10, 255, 256, 640, 641, 1000, 32768, 65534, 65535]),
    'u32': (4294967295, [3, 7, 10, 27, 641, 1000, 65537, 4294967295],
            [0, 1, 2, 26, 27, 641, 65535, 65536, 65537, 1000000007, 2147483648, 4294967294, 4294967295]),
}
out = ['''// GENERATED by gen_div_narrow.py (expected values come from Python integer arithmetic). Narrow unsigned division / modulo by literals (not powers of two).
import "../stdlib/libc.caspien"
import "../stdlib/gt/*"

func check(name: static imut string, ok: imut bool) void{
	unsafe extern{
		if ok{ printf("PASS %s\\n", name) }
		else{ printf("FAIL %s\\n", name) }
	}
}
''']
checks = []
for t, (mx, ks, vs) in T.items():
    for k in ks:
        out.append('@dont(inline)\nfunc dq_%s_%d(a: mut %s) mut %s{\n\treturn a / %d\n}\n' % (t, k, t, t, k))
        out.append('@dont(inline)\nfunc dm_%s_%d(a: mut %s) mut %s{\n\treturn a %% %d\n}\n' % (t, k, t, t, k))
        for i, v in enumerate(vs):
            checks.append('\tcheck("%s_%d_%d", dq_%s_%d(wrap:<%s>(%d)) == %d && dm_%s_%d(wrap:<%s>(%d)) == %d)'
                          % (t, k, i, t, k, t, v, v // k, t, k, t, v, v % k))
out.append('func main() void{')
out += checks
out.append('}')
print('\n'.join(out))
