#!/usr/bin/env python3
"""Generates tests/perf_codegen_test.caspien. Expected values come from this Python model, not hand arithmetic."""
M=(1<<64)-1
# 1. fully unrolled loops that use the induction variable
acc=0
for i in range(8): acc=(acc*3+i*i+7)&M
e_unroll1=acc
t=0
for i in range(6):
    for j in range(5): t+=i*10+j*j
e_unroll2=t
# 2. small constant memcopy: copy low 4 bytes / all 8 bytes
src=0x1122334455667788; dst=0xAABBCCDDEEFF0011
e_cp4=(dst & ~0xFFFFFFFF)|(src&0xFFFFFFFF); e_cp8=src; e_cp2=(dst & ~0xFFFF)|(src&0xFFFF); e_cp1=(dst & ~0xFF)|(src&0xFF)
# 3. struct element scalar fields in a dynarray
vals=[(i*1000003+17, (i*77+5)&0xFFFFFFFF) for i in range(9)]
e_sv=sum(v for v,_ in vals)&M; e_sw=sum(w for _,w in vals)&M
e_alt=sum(vals[i][0]-vals[i][1] for i in range(0,9,2))&M
# 4. int vars assigned from call results
def f(x): return (x*x+3*x+1)&M
def g(x): return (x^0x5555)+1
s=0
for i in range(12):
    a=f(i); b=g(a&0xFF); s=(s+a*b-i)&M
e_call=s
# 5. full HashMap (probing wraps)
keys=[3,11,19,27,35,43,51,59]
e_hm=sum(k*2 for k in keys)
L=[]
w=L.append
w("// GENERATED by tests/gen_perf_codegen.py -- do not edit. Covers: induction variable substituted in fully unrolled loops, small constant memcopy,")
w("// scalar struct-field reads/writes of dynarray elements, int variables assigned from call results (register pairs), full HashMap (probe wrap-around).")
for m in ["libc","gt_init","gt_register","gt_alive_check","gt_destruct","gt_moved","insecure_hash","dynamic_array","hash_map"]:
    w('import "../stdlib/%s.caspien"'%m)
w("""
struct Node{@pub{
	value: mut u64
	w: mut u32
}}

func check(name: static imut string, ok: mut bool) void{
	unsafe extern{
		if ok{
			printf("PASS %%s\\n", name)
		}else{
			printf("FAIL %%s\\n", name)
		}
	}
	return
}

func f(x: mut u64) mut u64{
	return x * x + 3 * x + 1
}
func g(x: mut u64) mut u64{
	return bits_xor(x, 21845) + 1
}

func unroll1() mut u64{
	let acc = mut 0
	for i in 0..8{
		acc = acc * 3 + i * i + 7
	}
	return acc
}
func unroll2() mut u64{
	let t = mut 0
	for i in 0..6{
		for j in 0..5{
			t = t + i * 10 + j * j
		}
	}
	return t
}
func copies(which: mut u64) mut u64{
	let:<mut u64> src = mut 0x1122334455667788
	let:<mut u64> dst = mut 0xAABBCCDDEEFF0011
	unsafe memcopy raw{
		if which == 1{ memcopy(raw dst, 1, raw src) }
		if which == 2{ memcopy(raw dst, 2, raw src) }
		if which == 4{ memcopy(raw dst, 4, raw src) }
		if which == 8{ memcopy(raw dst, 8, raw src) }
	}
	return dst
}
func calls() mut u64{
	let s = mut 0
	for i in 0..12{
		let a = mut f(i)
		let b = mut g(bits_and(a, 255))
		s = s + a * b - i
	}
	return s
}

func main() void{
	?catch(e){ return }
	check("unroll induction 1", unroll1() == %d)
	check("unroll induction 2 (nested)", unroll2() == %d)
	check("memcopy 1", copies(1) == %d)
	check("memcopy 2", copies(2) == %d)
	check("memcopy 4", copies(4) == %d)
	check("memcopy 8", copies(8) == %d)
	check("call results in int vars", calls() == %d)
	let nodes = mut ? dyn:<Node>([])
	let z = mut Node{value= 0, w= 0}
	nodes = ? resize(nodes, 9, z)
	for i in 0..9{
		match i into nodes{
			nodes[i].value = i * 1000003 + 17
			nodes[i].w = wrap:<u32>(i * 77 + 5)
		}
	}
	let sv = mut 0
	let sw = mut 0
	let alt = mut 0
	for i in 0..9{
		match i in nodes{
			sv = sv + nodes[i].value
			sw = sw + nodes[i].w as u64
			if i %% 2 == 0{
				alt = alt + nodes[i].value - nodes[i].w as u64
			}
		}
	}
	check("struct field sum value", sv == %d)
	check("struct field sum w", sw == %d)
	check("struct field mixed", alt == %d)
	let m = mut ? new HashMap:<u64>(mut 0, mut 0, mut 8)
	let ks = mut ? dyn([3, 11, 19, 27, 35, 43, 51, 59])
	for i in 0..8{
		match i in ks{
			m.set(m, ks[i], ks[i] * 2)
		}
	}
	let hs = mut 0
	for i in 0..8{
		match i in ks{
			hs = hs + m.get(m, ks[i], mut 0)
		}
	}
	check("full HashMap count", m.count == 8)
	check("full HashMap sum", hs == %d)
	check("full HashMap miss", m.get(m, mut 100, mut 999) == 999)
}
""" % (e_unroll1,e_unroll2,e_cp1,e_cp2,e_cp4,e_cp8,e_call,e_sv,e_sw,e_alt,e_hm))
open("tests/perf_codegen_test.caspien","w").write("\n".join(L)+"\n")
