#!/usr/bin/env python3
"""Generates tests/div_const_test.caspien: unsigned 64-bit division and modulo by literal divisors, checked against a Python model of the same xorshift stream."""
M=(1<<64)-1
divs1=[3,5,6,7,9,10,11,12,13,25,27,60,100,125,255,641,1000,1023,65535,65537,1000003,4294967295,4294967297,(1<<40)+1,(1<<62)+1,(1<<63)-1,0x8000000000000001,0xFFFFFFFFFFFFFFFF-1,0xFFFFFFFFFFFFFFFF]
# second file: even divisors (pre-shift magic), 64-bit magic without fix-up, big and small mixes
divs2=[14,18,20,24,28,40,48,56,96,112,136,139968,2000,4000,1000000,1000000007,(1<<32)+2,(3<<40),(5<<50)+(1<<49),(1<<62)+2,(1<<63)+2,(1<<63)+(1<<62),0xFFFFFFFFFFFFFFFC,0x7FFFFFFFFFFFFFFE,2147483647,2147483649,100003,641*1024,3<<62]
N=600
def xs(s):
    s^=(s<<13)&M; s^=s>>7; s^=(s<<17)&M; return s
def stream():
    s=88172645463325252
    for i in range(N):
        s=xs(s)
        yield s
        yield s>>(7+i%50)
        yield (~s)&M
        yield (s|((1<<(i%64))-1))&M
def gen(divs, path, title):
    out=[]
    w=out.append
    w("// Unsigned 64-bit division and modulo by literal divisors (the reciprocal-multiplication path of R_DIVC). GENERATED by tests/gen_div_const.py -- do not edit.")
    w("// For every divisor, a xorshift64 stream (with shifted, complemented and low-bit-filled variants of each value) is divided; the quotients and remainders are xor-folded")
    w("// and compared with the same fold computed by the Python model.")
    w("extern printf(static imut string,...) void")
    for idx,d in enumerate(divs):
        aq=ar=0
        for n in stream():
            aq^=n//d; ar^=n%d
        w("func check%d() mut u64{"%idx)
        w("\tunsafe extern{")
        w("\t\tlet fails = mut 0")
        w("\t\tlet s = mut 88172645463325252")
        w("\t\tlet aq = mut 0")
        w("\t\tlet ar = mut 0")
        w("\t\tfor i in 0..%d{"%N)
        w("\t\t\ts = bits_xor(s, bits_left(s, 13))")
        w("\t\t\ts = bits_xor(s, bits_right(s, 7))")
        w("\t\t\ts = bits_xor(s, bits_left(s, 17))")
        w("\t\t\tlet v1 = mut bits_right(s, (7 + (i % 50)))")
        w("\t\t\tlet v2 = mut bits_not(s)")
        w("\t\t\tlet v3 = mut bits_or(s, (bits_left(1, (i % 64)) - 1))")
        for v in ("s","v1","v2","v3"):
            w("\t\t\taq = bits_xor(aq, %s / %s)"%(v,hex(d)))
            w("\t\t\tar = bits_xor(ar, %s %% %s)"%(v,hex(d)))
        w("\t\t}")
        w("\t\tif aq != %s{"%hex(aq)); w("\t\t\tfails += 1"); w('\t\t\tprintf("FAIL div %s\\n")'%hex(d)); w("\t\t}")
        w("\t\tif ar != %s{"%hex(ar)); w("\t\t\tfails += 1"); w('\t\t\tprintf("FAIL mod %s\\n")'%hex(d)); w("\t\t}")
        w("\t\treturn fails")
        w("\t}")
        w("}")
    w("func main() void{")
    w("\tunsafe extern{")
    w("\t\tlet fails = mut 0")
    for idx in range(len(divs)):
        w("\t\tfails += check%d()"%idx)
    w('\t\tif fails == 0{'); w('\t\t\tprintf("PASS %s: %d divisors\\n", %d)'%(title,len(divs),len(divs))); w('\t\t}')
    w("\t}")
    w("}")
    open(path,'w').write("\n".join(out)+"\n")

gen(divs1, '/home/claude/caspien/tests/div_const_test.caspien', 'div_const')
gen(divs2, '/home/claude/caspien/tests/div_const2_test.caspien', 'div_const2')
