#!/usr/bin/env python3
"""Generates copy_forward_test.caspien. Cases for CopyForwardPass (a temporary holding a copy of a register variable is replaced by the variable),
the one-instruction narrow R_SETV (u8/u16/u32 variables assigned from temporaries) and the 3-operand multiply for non-power-of-two array strides
(struct elements of 24 and 40 bytes). Expected values come from the plain Python models below, not from the compiler.
Run: python3 gen_copy_forward.py > copy_forward_test.caspien"""
M = (1 << 64) - 1

def m_cpstore(n):
    a, b = 0, 1
    arr = [0, 0, 0, 0]
    for i in range(n):
        t = a
        arr[i % 4] = (t + b) & M
        a = (t + i) & M
        b = (b + 3) & M
    return (arr[0] + arr[1] * 3 + arr[2] * 5 + arr[3] * 7 + a + b) & M

def m_swap(n):
    x, y = 3, 5
    for i in range(n):
        t = x
        x = y + i
        y = t * 3 + 1
        y &= M
    return (x * 31 + y) & M

def m_narrow(n):
    a = 0; b = 0; c = 0; s = 0
    for i in range(n):
        a = (a * 3 + i) & 0xFF
        b = (b * 7 + a + i) & 0xFFFF
        c = (c * 1000003 + b + a) & 0xFFFFFFFF
        s = (s + a + b + c) & M
    return s

def m_stride24(n):
    a = [i * 7 + 3 for i in range(64)]
    b = [i * i + 11 for i in range(64)]
    s = 0
    for i in range(n):
        a[i] = a[i] + b[(i * 5) % 64]
    for i in range(64):
        s = (s + a[i] * 3 + b[i]) & M
    return s

def m_stride40(n):
    f = [[i + 1, i * 2 + 2, i * 3 + 3, i * 4 + 4] for i in range(64)]
    s = 0
    for i in range(n):
        j = (i * 3 + 1) % 64
        f[i][2] = f[i][2] + f[j][3]
        f[j][0] = f[j][0] + f[i][1]
    for i in range(64):
        s = (s + f[i][0] + f[i][1] * 2 + f[i][2] * 3 + f[i][3] * 5) & M
    return s

def m_chain(n):
    s = 0; k = 1
    for i in range(n):
        t = k
        u = t
        s = (s + u * 5 + t) & M
        k = (k * 3 + i) & M
    return s

def m_readn(n):
    s = 0
    for i in range(64):
        x8 = (i * 37 + 11) & 0xFF
        x16 = (i * 1009 + 7) & 0xFFFF
        x32 = (i * 1000003 + 5) & 0xFFFFFFFF
        s = (s + x8 * 3 + x16 * 5 + x32 * 7 + n) & M
        if x8 > 100: s = (s + 1) & M
        if x16 > 30000: s = (s + 2) & M
        if x32 > 100000000: s = (s + 4) & M
    return s

def m_masks(n):
    s = 0
    k = 0x9E3779B97F4A7C15
    x = 1
    for i in range(n):
        x = (x * k + i) & M
        a = x & 0xFF
        b = x & 0xFFFF
        c = x & 0xFFFFFFFF
        s = (s + a + b * 3 + c * 5) & M
    return s

NS = [0, 1, 2, 3, 7, 40, 255, 1000]
out = []
out.append('''// GENERATED by gen_copy_forward.py (expected values come from its Python models). Covers CopyForwardPass (copy of a register variable read through a
// temporary: stores, swaps, chains), narrow variables assigned from temporaries (u8/u16/u32 R_SETV) and non-power-of-two element strides (24 and 40).
import "../stdlib/libc.caspien"
import "../stdlib/gt/*"

struct Big{
	@pub{ a: mut u64 }
	@pub{ b: mut u64 }
}

struct Wide{
	@pub{ p: mut u64 }
	@pub{ q: mut u64 }
	@pub{ r: mut u64 }
	@pub{ s: mut u64 }
}

func check(name: static imut string, ok: imut bool) void{
	unsafe extern{
		if ok{ printf("PASS %s\\n", name) }
		else{ printf("FAIL %s\\n", name) }
	}
}

@dont(inline)
func cpstore(n: mut u64) mut u64{
	let a = mut 0
	let b = mut 1
	let r = mut 0
	unsafe udyn{
		let arr = mut unsafe dyn:<u64>([])
		arr = resize(arr, 4)
		for z in 0..4{
			arr[z] = 0
		}
		for i in 0..n{
			let t = a
			arr[i % 4] = t + b
			a = t + i
			b = b + 3
		}
		r = arr[0] + arr[1] * 3 + arr[2] * 5 + arr[3] * 7
	}
	return r + a + b
}

@dont(inline)
func swapv(n: mut u64) mut u64{
	let x = mut 3
	let y = mut 5
	for i in 0..n{
		let t = x
		x = y + i
		y = t * 3 + 1
	}
	return x * 31 + y
}

@dont(inline)
func narrow(n: mut u64) mut u64{
	let:<mut u8> a = mut wrap:<u8>(0)
	let:<mut u16> b = mut wrap:<u16>(0)
	let:<mut u32> c = mut wrap:<u32>(0)
	let s = mut 0
	for i in 0..n{
		a = wrap:<u8>(wrap:<u64>(a) * 3 + i)
		b = wrap:<u16>(wrap:<u64>(b) * 7 + wrap:<u64>(a) + i)
		c = wrap:<u32>(wrap:<u64>(c) * 1000003 + wrap:<u64>(b) + wrap:<u64>(a))
		s = s + wrap:<u64>(a) + wrap:<u64>(b) + wrap:<u64>(c)
	}
	return s
}

@dont(inline)
func chain(n: mut u64) mut u64{
	let s = mut 0
	let k = mut 1
	for i in 0..n{
		let t = k
		let u = t
		s = s + u * 5 + t
		k = k * 3 + i
	}
	return s
}

@dont(inline)
func readn(n: mut u64) mut u64{
	let s = mut 0
	unsafe udyn{
		let b8 = mut unsafe dyn:<u8>([])
		let b16 = mut unsafe dyn:<u16>([])
		let b32 = mut unsafe dyn:<u32>([])
		b8 = resize(b8, 64)
		b16 = resize(b16, 64)
		b32 = resize(b32, 64)
		for i in 0..64{
			b8[i] = wrap:<u8>(i * 37 + 11)
			b16[i] = wrap:<u16>(i * 1009 + 7)
			b32[i] = wrap:<u32>(i * 1000003 + 5)
		}
		for i in 0..64{
			let:<mut u8> x8 = mut b8[i]
			let:<mut u16> x16 = mut b16[i]
			let:<mut u32> x32 = mut b32[i]
			s = s + wrap:<u64>(x8) * 3 + wrap:<u64>(x16) * 5 + wrap:<u64>(x32) * 7 + n
			if x8 > 100{ s = s + 1 }
			if x16 > 30000{ s = s + 2 }
			if x32 > 100000000{ s = s + 4 }
		}
	}
	return s
}

@dont(inline)
func masks(n: mut u64) mut u64{
	let s = mut 0
	let x = mut 1
	for i in 0..n{
		x = x * 11400714819323198485 + i
		let a = mut bits_and(x, 255)
		let b = mut bits_and(x, 65535)
		let c = mut bits_and(x, 4294967295)
		s = s + a + b * 3 + c * 5
	}
	return s
}

@dont(inline)
func stride24(n: mut u64) mut u64{
	let s = mut 0
	unsafe udyn{
		let d = mut unsafe dyn:<Big>([])
		d = resize(d, 64)
		for i in 0..64{
			d[i].a = i * 7 + 3
			d[i].b = i * i + 11
		}
		for i in 0..n{
			d[i].a = d[i].a + d[(i * 5) % 64].b
		}
		for i in 0..64{
			s = s + d[i].a * 3 + d[i].b
		}
	}
	return s
}

@dont(inline)
func stride40(n: mut u64) mut u64{
	let s = mut 0
	unsafe udyn{
		let d = mut unsafe dyn:<Wide>([])
		d = resize(d, 64)
		for i in 0..64{
			d[i].p = i + 1
			d[i].q = i * 2 + 2
			d[i].r = i * 3 + 3
			d[i].s = i * 4 + 4
		}
		for i in 0..n{
			let j = mut ((i * 3 + 1) % 64)
			d[i].r = d[i].r + d[j].s
			d[j].p = d[j].p + d[i].q
		}
		for i in 0..64{
			s = s + d[i].p + d[i].q * 2 + d[i].r * 3 + d[i].s * 5
		}
	}
	return s
}

func main() void{''')
for name, model, ns in [('cpstore', m_cpstore, NS), ('swapv', m_swap, NS), ('narrow', m_narrow, NS), ('chain', m_chain, NS), ('readn', m_readn, NS), ('masks', m_masks, NS),
                        ('stride24', m_stride24, [1, 2, 3, 7, 40, 64]), ('stride40', m_stride40, [1, 2, 3, 7, 40, 64])]:
    for n in ns:
        out.append('\tcheck("%s_%d", %s(%d) == %d)' % (name, n, name, n, model(n)))
out.append('}')
print('\n'.join(out))
