#!/bin/bash
# `loop-unroll-nested` (tests/nested_unroll_test.caspien, generated by gen_nested_unroll.py): all 8 results are right with the switch on and off
# (and with loop-unrolling off), with it on the optimized bytecode is shorter than with it off (the substituted literals fold away), and while
# loop-unrolling is off the switch changes nothing (identical optimized bytecode).
# Needs Linux, java, gcc.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
W=$(mktemp -d); trap 'rm -rf "$W"' EXIT
export JAVA_TOOL_OPTIONS=
tar -C "$ROOT" --exclude=.git --exclude=.cache -cf - . | tar -C "$W" -xf -
cd "$W" || exit 1
sed -i 's/^target .*/target linux/; s/^\( *\)default: win64/\1default: sysv_x64/' toolchain.config
fail(){ echo "FAIL: $*"; exit 1; }
T=tests/nested_unroll_test.caspien
cfg(){ sed -i "s/^loop-unrolling: .*/loop-unrolling: $1/; s/^loop-unroll-nested: .*/loop-unroll-nested: $2/" toolchain.config; }
labels(){ java Compiler --no-cache -i $T output/nu >msg.txt 2>&1 || { cat msg.txt; fail "compile ($1)"; }; ./output/nu >run.txt
  [ "$(grep -c '^PASS' run.txt)" = 8 ] && ! grep -q FAIL run.txt || { cat run.txt; fail "results wrong ($1)"; }
  cp output/.build/2_optimizer.hob.txt "hob.$2"; wc -l < output/.build/2_optimizer.hob.txt; }
cfg aggressive off; off=$(labels "aggressive, nested off" a_off)
cfg aggressive on;  on=$(labels "aggressive, nested on" a_on)
cfg off off;        n1=$(labels "unrolling off, nested off" o_off)
cfg off on;         n2=$(labels "unrolling off, nested on" o_on)
echo "optimized lines: aggressive nested off $off, nested on $on; unrolling off $n1 / $n2"
[ "$on" -lt "$off" ] || fail "nested on did not shorten the code ($on >= $off)"
cmp -s hob.o_off hob.o_on || fail "the switch must change nothing while loop-unrolling is off"
echo "PASS nested_unroll_check"
