#!/usr/bin/env python3
"""Generates tests/sha256_test.caspien for stdlib/sha256.caspien. Every expected digest comes from Python's hashlib (the FIPS 180-4
vectors are additionally asserted here); no digest is typed by hand.   usage: python3 tests/sha256_gen.py > tests/sha256_test.caspien
The test is TABLE-DRIVEN on purpose: cases live in `let static` arrays and each kind of check has one call site inside a loop, because with
function-inlining aggressive every call site of `sha256` becomes a private copy of the whole hash (hundreds of call sites ran the Optimizer
out of memory)."""
import hashlib, struct, sys

H = lambda b: hashlib.sha256(b).hexdigest()
assert H(b"") == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
assert H(b"abc") == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
assert H(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq") == "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
assert H(b"a" * 1000000) == "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0"


def pat(n):  # byte(i) = (i*37 + 11) mod 256, the same as fillPattern in the test
    return bytes((i * 37 + 11) & 255 for i in range(n))


def words(digest_hex):
    return struct.unpack(">8I", bytes.fromhex(digest_hex))


def table(name, vals):
    n = len(vals)
    assert n * 4 != 8
    return "let static:<mut u32[%d]> %s = mut [%s]" % (n, name, ", ".join("0x%08x" % v for v in vals))


STD = [b"", b"abc", b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
       b"abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu",
       b"The quick brown fox jumps over the lazy dog"]
assert len(STD[3]) == 112
LENS = [0, 1, 2, 3, 4, 5, 8, 15, 16, 17, 31, 32, 33, 54, 55, 56, 57, 58, 62, 63, 64, 65, 66, 100, 118, 119, 120, 121, 126, 127, 128, 129,
        183, 184, 185, 191, 192, 193, 255, 256, 257, 1000]
CHUNKS = [1, 3, 7, 63, 64, 65, 100]
BLK = [0, 3, 16, 55]
LEAF = [(12345, 0), (3141592653, 7), (0, 140000), (4294967295, 1), (987654321, 4294967296 + 5), (1 << 32, 3)]
NODE = [(hashlib.sha256(bytes([t, 1])).digest(), hashlib.sha256(bytes([t, 2])).digest()) for t in range(4)]

o = []
w = o.append
w('''// Tests for stdlib/sha256.caspien: SHA-256 (FIPS 180-4) written in Caspien with the bitwise builtins.
// GENERATED by tests/sha256_gen.py -- every expected digest comes from Python's hashlib (the FIPS vectors "", "abc", the 56-byte
// "abcdbcde...nopq" and one million 'a' are asserted in the generator as well); nothing is typed by hand. Do not edit; edit the generator.
// TABLE-DRIVEN (cases in `let static` arrays, one call site per kind of check, because with function-inlining aggressive each call site
// of `sha256` is a private copy of the hash).
// Covered: the one-shot `sha256` on the standard strings (the 112-byte one, "The quick brown fox...") and one million 'a'; on a patterned
// message of length 0..1000 including every padding boundary (55 56 57 63 64 65 119 120 121 127 128 129 ...); the streaming API
// (`sha256Begin/Update/Finish/Release`) with 7 chunk sizes on 14 lengths, against hashlib AND the one-shot result, plus a million 'a' in
// several splits; the block primitives `sha256Compress` (bytes) and `sha256CompressWords` (16 words) in the exact shapes the Merkle
// benchmark uses (a 16-byte leaf message in one block, a 64-byte node message in two blocks, the second one pure padding) and on padded
// single-block messages; `sha256Init` / `sha256Digest`.
// Prints PASS/FAIL per check and a summary; the output must be identical with every optimisation switch off and on.
import "../stdlib/libc.caspien"
import "../stdlib/sha256.caspien"
import "../stdlib/gt_init.caspien"
import "../stdlib/gt_register.caspien"
import "../stdlib/gt_alive_check.caspien"
import "../stdlib/gt_destruct.caspien"
import "../stdlib/gt_moved.caspien"

let static passed = mut 0
let static failed = mut 0
''')
w("let static nStd = mut %d" % len(STD))
w("let static nPat = mut %d" % len(LENS))
w("let static nChunk = mut %d" % len(CHUNKS))
w("let static nStream = mut %d" % 14)
w("let static nBlk = mut %d" % len(BLK))
w("let static nLeaf = mut %d" % len(LEAF))
w("let static nPass = mut 3")
w("let static nThousand = mut 1000")
w("let static nBlocks64 = mut 15625")
w("let static nNode = mut %d" % len(NODE))
w(table("patLen", LENS))
w(table("patExp", [x for n in LENS for x in words(H(pat(n)))]))
w(table("chunkSize", CHUNKS))
w(table("blkLen", BLK))
w(table("blkExp", [x for n in BLK for x in words(H(pat(n)))]))
bs = lambda v: int.from_bytes(struct.pack('<I', v), 'big')
w(table("leafIn", [x for d, i in LEAF for x in (d & 0xffffffff, d >> 32, i & 0xffffffff, i >> 32)]))
w(table("leafExp", [x for d, i in LEAF for x in words(H(struct.pack('<QQ', d, i)))]))
w(table("nodeIn", [x for L, R in NODE for x in struct.unpack(">16I", L + R)]))
w(table("nodeExp", [x for L, R in NODE for x in words(H(L + R))]))
w('''
func pass(name: static imut string) void{
	unsafe{
		passed++
		printf("PASS %s\\n", name)
	}
}
func fail(name: static imut string) void{
	unsafe{
		failed++
		printf("FAIL %s\\n", name)
	}
}
// PASS/FAIL line with one number in the name
func reportN(name: static imut string, n: mut u64, ok: mut bool) void{
	unsafe{
		if ok{
			passed++
			printf("PASS %s %llu\\n", name, n)
		}else{
			failed++
			printf("FAIL %s %llu\\n", name, n)
		}
	}
}
func reportNN(name: static imut string, n: mut u64, m: mut u64, ok: mut bool) void{
	unsafe{
		if ok{
			passed++
			printf("PASS %s %llu / %llu\\n", name, n, m)
		}else{
			failed++
			printf("FAIL %s %llu / %llu\\n", name, n, m)
		}
	}
}
func report(name: static imut string, ok: mut bool) void{
	if ok{
		pass(name)
	}else{
		fail(name)
	}
}
func nibble(v: mut u64) mut u8{
	if v < 10{
		return wrap:<u8>(48 + v)
	}
	return wrap:<u8>(87 + v)
}
// true when the 32 digest bytes at d, as lowercase hex, equal the 64 characters of `expected`
func digestIs(d: raw imut u8, expected: static imut string) mut bool{
	let ok = mut true
	unsafe{
		let exp = mut malloc(mut 65)
		memcopy(exp, mut 64, expected)
		for i in 0..32{
			let v = mut deref(d + i) as u64
			let hi = mut nibble(bits_right(v, 4))
			let lo = mut nibble(bits_and(v, 15))
			if deref(exp + (2 * i)) != hi{
				ok = false
			}
			if deref(exp + (2 * i + 1)) != lo{
				ok = false
			}
		}
		free(exp)
	}
	return ok
}
// the 4 digest bytes at d + 4k read as one big-endian word
func beWord(d: raw imut u8, k: mut u64) mut u32{
	let:<mut u32> r = mut 0
	unsafe{
		let b0 = mut deref(d + 4 * k) as u32
		let b1 = mut deref(d + (4 * k + 1)) as u32
		let b2 = mut deref(d + (4 * k + 2)) as u32
		let b3 = mut deref(d + (4 * k + 3)) as u32
		r = bits_or(bits_or(bits_left(b0, 24), bits_left(b1, 16)), bits_or(bits_left(b2, 8), b3))
	}
	return r
}
// digest bytes against table row c of `patExp` (8 words per row)
func matchesPat(d: raw imut u8, c: mut u64) mut bool{
	let ok = mut true
	unsafe{
		for k in 0..8{
			let idx = mut (c * 8 + k)
			match idx in patExp{
				if beWord(d, k) != patExp[idx]{
					ok = false
				}
			}
		}
	}
	return ok
}
func fillPattern(buf: raw mut u8, n: mut u64) void{
	unsafe{
		for i in 0..n{
			let v = mut wrap:<u8>(i * 37 + 11)
			memcopy(buf + i, mut 1, raw v)
		}
	}
}
func put32(p: raw mut u32, i: mut u64, v: mut u32) void{
	unsafe{
		memcopy(p + i, mut 4, raw v)
	}
}
func bswap32(v: mut u32) mut u32{
	let b0 = mut bits_right(v, 24)
	let b1 = mut bits_and(bits_right(v, 8), 0xff00)
	let b2 = mut bits_and(bits_left(v, 8), 0xff0000)
	let b3 = mut bits_left(v, 24)
	return bits_or(bits_or(b0, b1), bits_or(b2, b3))
}
// state words (as the digest bytes of the state) against a row of a table
func stateMatches(st: raw imut u32, which: mut u64, c: mut u64) mut bool{
	let ok = mut true
	unsafe{
		let dig = mut malloc(mut 32)
		sha256Digest(st, dig)
		for k in 0..8{
			let idx = mut (c * 8 + k)
			if which == 0{
				match idx in blkExp{
					if beWord(dig, k) != blkExp[idx]{
						ok = false
					}
				}
			}
			if which == 1{
				match idx in leafExp{
					if beWord(dig, k) != leafExp[idx]{
						ok = false
					}
				}
			}
			if which == 2{
				match idx in nodeExp{
					if beWord(dig, k) != nodeExp[idx]{
						ok = false
					}
				}
			}
		}
		free(dig)
	}
	return ok
}
func sameWords(a: raw imut u32, b: raw imut u32) mut bool{
	let ok = mut true
	unsafe{
		for i in 0..8{
			if deref(a + i) != deref(b + i){
				ok = false
			}
		}
	}
	return ok
}
func stdString(k: mut u64) static imut string{''')
for i, m in enumerate(STD):
    w('\tif k == %d{\n\t\treturn "%s"\n\t}' % (i, m.decode()))
w('\treturn ""\n}\nfunc stdExpected(k: mut u64) static imut string{')
for i, m in enumerate(STD):
    w('\tif k == %d{\n\t\treturn "%s"\n\t}' % (i, H(m)))
w('''	return ""
}

func main() void{
	unsafe{
	// ---- one-shot on the standard strings (one call site, looped)
	for k in 0..nStd{
		unsafe{
			let s = imut stdString(k)
			let n = mut strlen(s)
			let buf = mut malloc(n + 1)
			let dig = mut malloc(mut 32)
			memcopy(buf, n, s)
			sha256(buf, n, dig)
			reportN("one-shot standard string, length", n, digestIs(dig, stdExpected(k)))
			free(buf)
			free(dig)
		}
	}
	// ---- one-shot and streaming on one million 'a' (cdc76e5c...)
	unsafe{
		let n = mut 1000000
		let buf = mut malloc(n)
		let dig = mut malloc(mut 32)
		for i in 0..n{
			let v = mut 97
			memcopy(buf + i, mut 1, raw v)
		}
		sha256(buf, n, dig)
		report("one-shot one million 'a'", digestIs(dig, "@@H@@"))
		let ctx = mut Sha256Ctx{state= null, pending= null, pendingCount= mut 0, totalCount= mut 0}
		for pass in 0..nPass{
			sha256Begin(auto ctx)
			if pass == 0{
				for k in 0..nThousand{
					sha256Update(auto ctx, buf + (k * 1000), mut 1000)
				}
			}
			if pass == 1{
				sha256Update(auto ctx, buf, mut 333333)
				sha256Update(auto ctx, buf, mut 0)
				sha256Update(auto ctx, buf, mut 1)
				sha256Update(auto ctx, buf, mut 666666)
			}
			if pass == 2{
				for k in 0..nBlocks64{
					sha256Update(auto ctx, buf + (k * 64), mut 64)
				}
			}
			sha256Finish(auto ctx, dig)
			sha256Release(auto ctx)
			reportN("streaming one million 'a', split pattern", pass, digestIs(dig, "@@H@@"))
		}
		free(buf)
		free(dig)
	}
	// ---- one-shot on patterned messages around every padding boundary
	for c in 0..nPat{
		unsafe{
			let n = mut 0
			match c in patLen{
				n = patLen[c] as u64
			}
			let buf = mut malloc(n + 1)
			let dig = mut malloc(mut 32)
			fillPattern(buf, n)
			sha256(buf, n, dig)
			reportN("one-shot patterned message, length", n, matchesPat(dig, c))
			free(buf)
			free(dig)
		}
	}
	// ---- streaming: several chunk sizes on 14 lengths, against hashlib and against the one-shot digest
	for c in 0..nPat{
		let sel = mut (c % 3)
		if c < nStream * 3{
			if sel == 0{
				for ci in 0..nChunk{
					unsafe{
						let n = mut 0
						match c in patLen{
							n = patLen[c] as u64
						}
						let chunk = mut 0
						match ci in chunkSize{
							chunk = chunkSize[ci] as u64
						}
						let buf = mut malloc(n + 1)
						let one = mut malloc(mut 32)
						let dig = mut malloc(mut 32)
						fillPattern(buf, n)
						sha256(buf, n, one)
						let ctx = mut Sha256Ctx{state= null, pending= null, pendingCount= mut 0, totalCount= mut 0}
						sha256Begin(auto ctx)
						let off = mut 0
						loop{
							if off >= n{
								break
							}
							let take = mut chunk
							if take > n - off{
								take = n - off
							}
							sha256Update(auto ctx, buf + off, take)
							off = off + take
						}
						sha256Finish(auto ctx, dig)
						sha256Release(auto ctx)
						let same = mut true
						for i in 0..32{
							if deref(one + i) != deref(dig + i){
								same = false
							}
						}
						reportNN("streaming patterned message, length / update size", n, chunk, matchesPat(dig, c) && same)
						free(buf)
						free(one)
						free(dig)
					}
				}
			}
		}
	}
	// ---- block primitives
	unsafe{
		let st = mut sha256NewState()
		let st2 = mut sha256NewState()
		let wd = mut sha256WordsAlloc(16)
		let blk = mut malloc(mut 64)
		let dig = mut malloc(mut 32)
		sha256Digest(st, dig)
		report("sha256NewState / sha256Digest: H0 first bytes 6a09e667", beWord(dig, 0) == 0x6a09e667 && beWord(dig, 7) == 0x5be0cd19)
		// sha256Compress and sha256CompressWords on the padded single block of an n-byte message
		for bi in 0..nBlk{
			let n = mut 0
			match bi in blkLen{
				n = blkLen[bi] as u64
			}
			sha256Init(st)
			sha256Init(st2)
			fillPattern(blk, n)
			let marker = mut 0x80
			memcopy(blk + n, mut 1, raw marker)
			let zero = mut 0
			let from = mut (n + 1)
			for i in from..64{
				memcopy(blk + i, mut 1, raw zero)
			}
			let bits = mut (n * 8)
			let lo = mut wrap:<u8>(bits)
			let hi = mut wrap:<u8>(bits_right(bits, 8))
			memcopy(blk + 63, mut 1, raw lo)
			memcopy(blk + 62, mut 1, raw hi)
			sha256Compress(st, blk)
			for k in 0..16{
				put32(wd, k, beWord(blk, k))
			}
			sha256CompressWords(st2, wd)
			reportN("sha256Compress on the padded block of a message of length", n, stateMatches(st, 0, bi))
			reportN("sha256CompressWords on the same block as 16 words, message length", n, stateMatches(st2, 0, bi) && sameWords(st, st2))
		}
		// Merkle leaf shape: SHA256(le64(d) || le64(i)), 16-byte message, one block of words (bswap32 of the little-endian halves)
		for li in 0..nLeaf{
			sha256Init(st)
			let b = mut (li * 4)
			let b1 = mut (b + 1)
			let b2 = mut (b + 2)
			let b3 = mut (b + 3)
			match b in leafIn{
			match b1 in leafIn{
			match b2 in leafIn{
			match b3 in leafIn{
				put32(wd, 0, bswap32(leafIn[b]))
				put32(wd, 1, bswap32(leafIn[b1]))
				put32(wd, 2, bswap32(leafIn[b2]))
				put32(wd, 3, bswap32(leafIn[b3]))
			}
			}
			}
			}
			put32(wd, 4, 0x80000000)
			for k in 5..15{
				put32(wd, k, 0)
			}
			put32(wd, 15, 128)
			sha256CompressWords(st, wd)
			reportN("Merkle leaf shape (16-byte message, one block), case", li, stateMatches(st, 1, li))
		}
		// Merkle node shape: SHA256(L || R), 64-byte message in two blocks, the second one pure padding, state carried over
		for ni in 0..nNode{
			sha256Init(st)
			for k in 0..16{
				let idx = mut (ni * 16 + k)
				match idx in nodeIn{
					put32(wd, k, nodeIn[idx])
				}
			}
			sha256CompressWords(st, wd)
			put32(wd, 0, 0x80000000)
			for k in 1..15{
				put32(wd, k, 0)
			}
			put32(wd, 15, 512)
			sha256CompressWords(st, wd)
			reportN("Merkle node shape (64-byte message, two blocks), case", ni, stateMatches(st, 2, ni))
		}
		sha256FreeState(st)
		sha256FreeState(st2)
		sha256WordsFree(wd)
		free(blk)
		free(dig)
	}
	unsafe{
		printf("sha256: %llu passed, %llu failed\\n", passed, failed)
		if failed == 0{
			printf("ALL SHA256 TESTS PASSED\\n")
		}
	}
	}
}''' .replace('@@H@@', H(b"a" * 1000000)))
sys.stdout.write("\n".join(o) + "\n")
