#!/bin/bash
# Strided struct-element access (tests/stride_index_test.caspien, generated by gen_stride_index.py): all 26 results right under the shipped, an
# everything-off and an aggressive config, and (shipped config) the generated assembly uses the fused form `disp(%base,%r15,1)` after
# `imulq $stride, %idx, %r15` instead of separate address arithmetic. Needs Linux, java, gcc.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
W=$(mktemp -d); trap 'rm -rf "$W"' EXIT
export JAVA_TOOL_OPTIONS=
tar -C "$ROOT" --exclude=.git --exclude=.cache -cf - . | tar -C "$W" -xf -
cd "$W" || exit 1
sed -i 's/^target .*/target linux/; s/^\( *\)default: win64/\1default: sysv_x64/' toolchain.config
fail(){ echo "FAIL: $*"; exit 1; }
T=tests/stride_index_test.caspien
run(){ java Compiler --no-cache -i $T output/si >msg.txt 2>&1 || { cat msg.txt; fail "compile ($1)"; }; ./output/si >run.txt
  [ "$(grep -c '^PASS' run.txt)" = 26 ] && ! grep -q FAIL run.txt || { cat run.txt; fail "results wrong ($1)"; }; }
run shipped
fused=$(grep -c ',%r15,1)' output/.build/4_codegen.s)
echo "fused strided accesses in the shipped-config assembly: $fused"
[ "$fused" -ge 20 ] || fail "expected the fused strided form in the assembly (found $fused)"
sed -i 's/^loop-unrolling: .*/loop-unrolling: aggressive/; s/^function-inlining: .*/function-inlining: aggressive/; s/^constant-folding: .*/constant-folding: on/; s/^loop-unroll-nested: .*/loop-unroll-nested: on/' toolchain.config
run aggressive
echo "PASS stride_index_check"
