package caspien;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

/**
 * CLI entry point.
 *
 * Usage: compiler -i main.caspien main.exe
 *
 * This build implements the full "first deliverable" pipeline: lex ->
 * parse -> RPN -> tree-build -> import-resolve -> dup-expand -> generics-
 * expand -> load compiler.config -> type-check -> bytecode generation.
 * compiler.config is a fixed path ("compiler.config", resolved
 * relative to the current working directory) and is required --
 * missing entirely is a fatal error, confirmed directly, never a
 * silently-applied built-in fallback (see CompilerConfig). Assembly
 * generation (bytecode -> real machine code) is
 * explicitly out of scope for this deliverable, per the project spec --
 * so the given output path receives the generated bytecode as plain
 * text, not an actual executable, despite the ".exe"-shaped CLI
 * argument. The bytecode is also printed to stdout and written to
 * output.txt for convenience. A separate debug.txt captures the raw
 * lexer output and the fully type-checked tree (with every node's
 * resolvedType annotated) for inspecting the pipeline's intermediate
 * state.
 */
public class Main {

    public static void main(String[] args) {
        try {
            run(args);
        } catch (CompilerException ce) {
            System.err.println(ce.getMessage());
            System.exit(1);
        } catch (IOException ioe) {
            System.err.println("[io error] " + ioe.getMessage());
            System.exit(1);
        }
    }

    private static void run(String[] args) throws IOException {
        if (args.length < 3 || !args[0].equals("-i")) {
            System.err.println("Usage: compiler -i <input.caspien> <output>");
            System.exit(1);
            return;
        }
        String inputPath = args[1];
        String outputPath = args[2];

        FsPolicy.current = FsPolicy.load("fs.config");
        FsPolicy.loadPlatform("platform.config");
        boolean fsReport = false;
        boolean audit = false;
        for (int i = 3; i < args.length; i++) {
            if (args[i].equals("--fs-report")) {
                fsReport = true;
            }
            if (args[i].equals("--audit")) {
                audit = true;
            }
        }
        DepsLog.record(inputPath);
        String source = new String(Files.readAllBytes(Paths.get(inputPath)), StandardCharsets.UTF_8);

        // "the target file should be stripped down to the base file
        // name," confirmed directly -- __FILENAME's own value for the
        // top-level file, regardless of how the compiler was actually
        // invoked (a bare name, a relative path, or an absolute one).
        String displayFile = Paths.get(inputPath).getFileName().toString();
        Lexer lexer = new Lexer(source, inputPath, displayFile);
        List<Token> tokens = lexer.tokenize();

        Parser parser = new Parser();
        List<Token> parsed = parser.parse(tokens);

        RpnConverter rpnConverter = new RpnConverter();
        rpnConverter.convertLines(parsed);

        TreeBuilder treeBuilder = new TreeBuilder();
        treeBuilder.buildLines(parsed);

        ImportResolver importResolver = new ImportResolver();
        List<Token> resolved = importResolver.resolve(parsed, inputPath);

        new DupExpander().expand(resolved);
        List<Token> expanded = new GenericsExpander().expand(resolved);

        CompilerConfig config = CompilerConfig.load("compiler.config");

        TypeChecker typeChecker = new TypeChecker(config);
        typeChecker.check(expanded);

        String auditReport = null;
        if (audit) {
            java.util.List<String> srcs = new java.util.ArrayList<>();
            for (String f : DepsLog.files()) {
                if (f.endsWith(".caspien")) {
                    srcs.add(f);
                }
            }
            String report = AuditReport.build(srcs, Paths.get("..").toAbsolutePath().normalize(), typeChecker.unsafeTagsNeeded(),
                    "1".equals(System.getenv("CASPIEN_AUDIT_NOSTDLIB")));
            auditReport = report;
        }

        BytecodeEmitter bytecodeEmitter = new BytecodeEmitter();
        String bytecode = bytecodeEmitter.emit(expanded, typeChecker);

        if (audit) {
            String report = auditReport + GasReport.build(bytecode).text;
            String target = System.getenv("CASPIEN_AUDIT_FILE");
            if (target != null && !target.isEmpty()) {
                Files.write(Paths.get(target), report.getBytes(StandardCharsets.UTF_8));
            } else {
                System.err.print(report);
            }
        }

        if (fsReport) {
            typeChecker.printFsReport(System.err);
        }
        System.out.print(bytecode);

        DepsLog.writeIfRequested();
        writeFile(outputPath, bytecode);
        writeFile("output.txt", bytecode);

        StringBuilder debug = new StringBuilder();
        debug.append("# Caspien lexer output for ").append(inputPath).append("\n\n");
        for (Token t : tokens) {
            debug.append(t.toString()).append("\n");
        }
        debug.append("\n# Caspien fully type-checked tree (every resolvedType annotated)\n\n");
        TreeDump.dumpLines(debug, expanded, 0);
        writeFile("debug.txt", debug.toString());

        System.err.println("\n[info] wrote bytecode to " + outputPath + " and output.txt ("
                + bytecode.lines().count() + " instructions/lines); debug tree written to debug.txt");
    }

    private static void writeFile(String path, String content) throws IOException {
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(Paths.get(path), StandardCharsets.UTF_8))) {
            pw.print(content);
        }
    }
}
